### ISSUE TITLE
This extension is not installable in certain regions

### ISSUE THREAD

**Issue by hsachinraj** [qetza/vsts-replacetokens-task#100]
Looks like there is a geography-specific loghic or dependency that the extension is not installable in certain regions. Importing a build pipeline that has this task fails with the error message:

Error while creating build definition: The pipeline is not valid. Job Phase_0: Step references task 'a8515ec8-7254-4ffd-912c-86772e2b5962' at version '' which does not exist.,Job Phase_0: Step references task 'a8515ec8-7254-4ffd-912c-86772e2b5962' at version '3.*' which does not exist.

**Comment by qetza** [comment]
Hi @hsachinraj,
Seems like the extension is not installed on your account, can you check in the manage extension page?

**Comment by hsachinraj** [comment]
Thanks @qetza  for the quick response. I use the extension in my [demo generator](https://azuredevopsdemogenerator.azurewebsites.net) and intermittently fails when the extension is installed - in certain regions like West Europe, South India, etc., Not sure why.

**Comment by qetza** [comment]
Hi @hsachinraj,
If i understand correctly your demo generator is creating a bunch of items in an azure devops account and on of this item is a pipeline using the replace token task and when running the pipeline it sometimes have issues?
My best guest would be that the extension is not installed on the account on which you import the pipeline.
From your profile it seems you work in Redmond, i'm on the MS campus this week so if you want we can try to meet to investigate your issue

**Comment by samaea** [comment]
Hi,

I am also facing the same issue unfortunately. It has been over 7 hours since I installed the extension and although it is installed, I cannot see or add tasks related to Replace Tokens.

Any thoughts (workarounds perhaps)?

**Comment by iorlas** [comment]
Same here, it is installed in organisation settings, all is in place, cache cleared, page reloaded, user authenticated. It is still no go :(

**Comment by qetza** [comment]
Hi,
I will try to investigate why this is happening with the MS teams and will fix the issue if anything is found.

**Comment by iorlas** [comment]
@qetza Just FYI, I'm using Cloud-hosted DevOps, worker pool is hosted Ubuntu and organisation is freshly created a few days ago. If any additional info could help you, just ping me :)

**Comment by qetza** [comment]
@iorlas could you tell me in which region you created your organisation and if possible its name?

**Comment by iorlas** [comment]
@qetza Yup! Central US it is. Org name is eugenevainshel, project Gospacey.

**Comment by iorlas** [comment]
@qetza Hey! Don't really know was it fixed automagically or you did something, but it it available now. There is a chance it appeared earlier, but anyway something was off. Just want you to know!

**Comment by Campanari** [comment]
Same here. I can't add "Replace Tokens" task.

![image](https://user-images.githubusercontent.com/2683641/56988711-159e2500-6b67-11e9-91fb-513d6a2a19e6.png)

**Comment by Campanari** [comment]
Two days after, it's working now.

**Comment by qetza** [comment]
Hi,
I had confirmation from MS that they were issues with their installation process (which is async) and are working on a fix. This should explain why the task appear after a long time.

**Comment by stephenmichaelf** [comment]
Yes we were experiencing some delays in extension task install. I apologize for that. We've added some additional resiliency to the process and it appears to have alleviated the issues.

If anyone is still seeing delays or sees them in the future please let me know. Thanks!

**Comment by fredrikker** [comment]
> Yes we were experiencing some delays in extension task install. I apologize for that. We've added some additional resiliency to the process and it appears to have alleviated the issues.
> 
> If anyone is still seeing delays or sees them in the future please let me know. Thanks!

I'm facing the same issue as previous poster @Campanari. The extension was installed three days ago but it still just says "Installed" when I try to add a task.

**Comment by stephenmichaelf** [comment]
@fredrikker I agree this is confusing, we have a ticket open with the team that owns the UI to make it more clear. Thanks for the feedback!

**Comment by iorlas** [comment]
> got confused by the different icons between the task and the actual plugin.

It is kind of generic problem in UI, it is not obvious how it should be solved, since one package could contain multiple tasks within, with different icons. But I would be happy if package would have any of such icons.

Maybe it even needs bigger overhaul. Like, introduce packages as UI element in tasks lists.

**Comment by qetza** [comment]
Closing as this is an issue on the Azure DevOps platform, feel free to reopen if needed.
