### ISSUE TITLE
How to use this extension?

### ISSUE THREAD

**Issue by kvansaders** [qetza/vsts-replacetokens-task#106]
I'm a little confused by the screen shot and documentation on how to actually map/replace appsettings or connection string values.  Can you post an example on replacing values named in appsettings, connection strings, or even otherwise if possible (like smtp settings)?

**Comment by qetza** [comment]
Hi @kvansaders,

Thanks for the feedback, i’ll add a sample file in the docs in the next release.

In the meantime here is an example:
In any text file if you put the string `#{SmtpServer}#` then if you declare in your pipeline a variable named ˋSmtpServer` the task will replace the previous token with the value of the variable. You can put as many tokens as you want.

Hopes this helps

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
