### ISSUE TITLE
Yaml Azure pipeline: Task 'replacetokens' is using deprecated task execution handler

### ISSUE THREAD

**Issue by Klippertjen** [qetza/vsts-replacetokens-task#108]
When using Replace Tokens in Yaml Azure pipeline the following warning is shown:

Task 'replacetokens' (1.4.1) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib

**Comment by qetza** [comment]
Hi @Klippertjen,

The version 1.4.1 is an old version which supports TFS 2015 and i haven't made any updates on it. Can you check which version of TFS/Azure DevOps you are using? If it's a newer one than TFS 2015 i would suggest upgrading the task to the latest version.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
