### ISSUE TITLE
How do we get it to run on the target server?

### ISSUE THREAD

**Issue by nanderto** [qetza/vsts-replacetokens-task#11]
I am trying to run it in release management (vNext) after copying my files to the target server. How do I run this task on them? it seems like this is set up to change files on my build server.

**Comment by qetza** [comment]
Hi @nanderto,
The way the build and release system works the task are executed on the agent and cannot be executed on a remote server (Microsoft is working on enabling deployment through local agent (https://blogs.msdn.microsoft.com/visualstudioalm/2016/04/13/release-management-planning-update-2016-h2/).
For now i would suggest, if you can, to first do the replacement on the agent then copy the files to your target server.

**Comment by nanderto** [comment]
OK thanks, and thanks for the suggestion although I don't think it's reasonable for us. Its not a great idea to have the production configuration exposed on a build server. Even if we create it and delete it after every transformation it would still be exposed briefly. We really need a task that will do the transformation on the target servers.
thanks again
noel
