### ISSUE TITLE
Option to use parameters file as well as variables

### ISSUE THREAD

**Issue by jonmartin136** [qetza/vsts-replacetokens-task#113]
Hi

I know something similar has been rasied previoulsy but the scenario here is slightly different. I'm already dynamically creating a VSTS variable that is then used by the Replace Tokens task but it has now reached the upper size limits for variables:

##[warning]Environment variable 'XXXX' exceeds the maximum supported length. Environment variable length: 41681 , Maximum supported length: 32766

If the task supported reading a parameters (token/value pairing) file as well as using the environment variables then instead of dynamically creating a variable I'd generate the parameters file.

The file format could be a simple text TOKEN = VALUE per line or more complex as JSON or XML format.

Thanks,

**Comment by qetza** [comment]
Hi @jonmartin136,

This is a good feedback, i'll add it to the backlog. Just need to defined what would be the user friendliest format.

**Comment by qetza** [comment]
Hi @jonmartin136,
This feature is now available in version 3.4.0
