### ISSUE TITLE
Fails on empty files

### ISSUE THREAD

**Issue by WhimsySpoon** [qetza/vsts-replacetokens-task#12]
We have noticed that when attempting to replace tokens in empty files, the task fails with the following error:

##[error]Cannot index into a null array

Would it be possible to skip empty files? I am told that we cannot delete these files as they are populated by the application at run time.

**Comment by qetza** [comment]
Hi @WhimsySpoon, thanks for reporting the issue.
The bug is fixed and should be in the next release (hopefully by tomorrow)

**Comment by WhimsySpoon** [comment]
Fantastic! Thank you very much for the quick response. As soon as the new version is available, I'll perform a test on the failing release and let you know of the results.

**Comment by WhimsySpoon** [comment]
I've copied the code from the commit and manually updated the functions script on the build agent. I'm delighted to report that it solves the issue. Do you know when this will be pushed into the marketplace?

**Comment by qetza** [comment]
I have 2 other features i want to finish for the next release. I'll finish them tonight and push the release on the marketplace just after.

**Comment by qetza** [comment]
Release 1.3.0 was pushed to the marketplace and contains the fix.
