### ISSUE TITLE
How do I specify multiple files in YAML?

### ISSUE THREAD

**Issue by henry-padilla** [qetza/vsts-replacetokens-task#120]
I want to build a nuget package so I need my *.psd1 and *.nuspec to have the same version number. I see 'targetFiles' is a newline separated list but I'm unclear about the YAML.

    inputs:
      targetFiles: '**/manifest.psd1
**/package.nuspec'

Or do I use `r`n?

    inputs:
      targetFiles: '**/manifest.psd1`r`n**/package.nuspec'

**Comment by henry-padilla** [comment]
Also, does this task run in the Build.ArtifactStagingDirectory, Build.SourcesDirectory, Pipeline.Workspace ...?

**Comment by qetza** [comment]
Hi @henry-padilla,
You can use comma or new line to separate files. If you want to use new line in YAML (more readable) here is the syntax:
```
inputs:
  targetFiles: |
    **/manifest.psd1
    **/package.nuspec
```
If you are in doubt with the YAML syntax you can always create a new pipeline using the UI, configure the task through the UI and click the `View YAML` link on the top right to see the corresponding YAML syntax :)

By default the root directory is `System.DefaultWorkingDirectory`. You can override this by setting the parameter `rootDirectory` like this:
```
inputs:
  rootDirectory: '$(Pipeline.Workpace)'
  targetFiles: |
    **/manifest.psd1
    **/package.nuspec
```

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
