### ISSUE TITLE
Warn if the file your trying to replace tokens in doesn't exist

### ISSUE THREAD

**Issue by davemanton** [qetza/vsts-replacetokens-task#126]
At present there is no feedback given if the file doesn't exist that you're trying to replace tokens in.

It would be really helpful if this was fed back in the console output and possibly the number of files where token replacement has occurred?

**Comment by qetza** [comment]
Hi @davemanton,
There is a log entry for each file found starting with `replacing tokens in:`. If i file was explicitly set and it doesn't exists there's an error log also.
I will see if i can think of a summary to display at the end of the task.

**Comment by qetza** [comment]
Hi @davemanton,
The version 3.4.0 now displays a summary (number of replaced tokens and number of files).
