### ISSUE TITLE
Secrets replaced as *** 

### ISSUE THREAD

**Issue by yesoreyeram** [qetza/vsts-replacetokens-task#129]
In my pipeline secrets are getting replaced as *****

My pipeline looks like this.
```

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: My Variables
  - name: DummyKeyValue
    value: $(DummyKey)
  - name: BUILDID
    value: $(Build.BuildId)
    
steps: 

  - task: replacetokens@3
    inputs:
      rootDirectory: './data/'
      targetFiles: 'version'
      encoding: 'auto'
      writeBOM: true
      actionOnMissing: 'warn'
      keepToken: false
      tokenPrefix: '#{'
      tokenSuffix: '}#'
  
  - script: |
        echo "-------------";
        cat ./data/version;
        echo "";
        echo "-------------";
        exit $?;
    displayName: Display Replaced File
```

my file /data/version looks like below

```
#{Build.BuildId}#
#{BUILDID}#
#{DummyKey}#
#{DummyKeyValue}#
#{DummyName}#
```

Then azure pipeline output replace tasks replaces like this..

![image](https://user-images.githubusercontent.com/153843/71819195-1e92af00-3083-11ea-93a5-f5200a8a8050.png)

I am not sure what i am doing wrong here. Any help is appreciated.

**Comment by qetza** [comment]
Hi @yesoreyeram,
It is a feature from the logs of the pipelines to replace all secret values by *** in the logs so that you cannot leak a secret.
Can you check in your file directly, the tokens should have been replaced with the secret values.

**Comment by yesoreyeram** [comment]
Yea .. you are correct. console masks the secrets. I have uploaded the file as artifact and then download. Seems the secret exist. Thanks a lot for the explanation.
```

- task: PublishPipelineArtifact@1
    inputs:
      targetPath:  './data/'
      artifact: tmp
```
