### ISSUE TITLE
Variables that come from Variable groups?

### ISSUE THREAD

**Issue by Bazul99** [qetza/vsts-replacetokens-task#130]
Seems like the task doesn't find variables that come from Variable groups?  Only Variables that come from Pipeline variables?

In my case I'm trying to sub machine keys into my Web.config (don't want them to be in source control and they live in <system.web> which normal variables substitution doesn't handle.  It makes sense to make set of Variable groups so all out pipelines get variables that map to environments (Dev, Test, Prod) that hold environment specific things like...machine keys but the task doesn't find variables from there only variables in the pipeline.  Yes, I can make a set for each stage (Dev, Test, Prod) but then I need to duplicate these across all my release pipelines instead of one time in a Variable group.

Is this a Feature request or am I doing something wrong that this task can handle?

**Comment by qetza** [comment]
Hi @Bazul99,

Sorry to tell you but you are doing something wrong as the task is working fine with variable groups (I'm using it every day). For tasks there is no difference between variables defined in the pipeline or in a variable group as it is the agent which is doing the merge of variables and exposing to tasks the result as a single list of available variables.

Could you share your how you configured your pipeline with the variable group?

**Comment by DanielEgan** [comment]
how do you reference the Variable Group in Yaml?  

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens'
  inputs:
    targetFiles: |
      **/*.config
      **/*.json => outputs/*.json

**Comment by qetza** [comment]
You can reference variable groups at the pipeline, stage or job level in YAML using the following syntax:
```yaml
variables:
  - group: {name-of-your-variable-group}
```

You can find all the documentation here: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#variables

**Comment by MichalKosowski** [comment]
Hi,

I am using multi-stage yml with templates and variable groups. Just got a strange issue here. Basically, task works fine, when variable is defined in yml file, but when trying to replace variables in xml files, I am getting warninig:

`##[debug]configCertificateThumbprint=undefined
##[warning]  variable not found: configCertificateThumbprint
`
What is interesting, I have added a bash task before that to print variable, and it is there:

`- bash: |
         echo "thumbprint is ${{parameters.configCertificateThumbprint}}"`

Output is:
_##[debug]script=echo "thumbprint is 67af512a7115b30aab8b46b0e2f042a08a92e0ce"
_

I was able to fix the issue adding following bash script:
`echo "##vso[task.setvariable variable=configThumbprint]${{parameters.configCertificateThumbprint}}"`

As already said, this is working without any problems for yml files, but breaking for xml... :/

**Comment by Bazul99** [comment]
I'm not sure what I was doing wrong to be honest but it was definitely me because it's working now perfectly.  Thanks!

**Comment by qetza** [comment]
Hi @MichalKosowski,
The issue is not XML but that you are trying to use a template parameter as a variable which is not possible (template parameters are expanded before running the pipeline and are not available during the run).
Your solution is the correct one, your script is creating a new variable with the template parameter value.

**Comment by MichalKosowski** [comment]
Hmm so why it was working when I was replacing variables in yml file? 🤔

**Comment by qetza** [comment]
Hi @MichalKosowski,
Without knowing your YML template i cannot say but here is the process when using templates:
- before executing the pipeline the template engine is run
- the template engine parses the template to generate the real YML pipeline, parameters are replaced by their values (simple find & replace) and loops and ifs are expanded
- then when the template is expanded this is the YML which is executed by the agent. So the agent doesn't know anything about template

If you need to use template parameters in tasks:
- if the value can be pass as a task parameter just assign the template parameter as the task parameter value
- if the value needs to be accessed dynamically (as the replace token task is doing) you need to create a variable that will hold the template parameter value. For this you can use your solution or i thought of another one: in your template declare at the stage or job level a variable and assign it the template parameter.

Here's an example:
```yaml
parameters:
  configCertificateThumbprint: ''

- job: myjob
  variables:
    configCertificateThumbprint: ${{parameters.configCertificateThumbprint}}
```

This will create a variable with the value of the template parameter and the pipeline will have access to it through `$(configCertificateThumbprint)` and tasks through the variables.
