### ISSUE TITLE
js file unable to properly escape

### ISSUE THREAD

**Issue by geedsen** [qetza/vsts-replacetokens-task#134]
We have the whole content of a .js file in a variable.  We merge this into a postman environment file (as an environment variable). The only thing is, in the .js file we need to escape all double quotes (") , that is no problem. But the javascript contains a regex expression that already has an escape in it "\\[". So somehow we need to escape that backslash as well, but only that backslash not any other ones.... I guess we need some regex possibilities for escaping.

**Comment by qetza** [comment]
Hi @geedsen,
Providing the ability to use your own regex for escaping may be a little complex.

As a workaround you could replace the part causing the issue with some other value before doing the replace token then after the replace token reinject the other value back.

**Comment by geedsen** [comment]
That is indeed what I did, thanks
