### ISSUE TITLE
Token replace not working properly

### ISSUE THREAD

**Issue by MustafaC114** [qetza/vsts-replacetokens-task#138]
Token #{api-gateway-url}#

Replaced Value set in Variables api-gateway-url=http://xyz.com/

File encoding is auto

Getting Value at the end http:\/\/xyz.com\/
I am using it in Azure Devops

**Comment by qetza** [comment]
Hi @MustafaC114 ,

Could you share some logs because i don't see the issue, your token seems to be replaced by the correct value `http://xyz.com/`

**Comment by MustafaC114** [comment]
sorry it get value at last http:/\/\xyz.com/\

**Comment by ma586** [comment]
I have the same issue.

**Comment by qetza** [comment]
Hi @ma586, @MustafaC114 

Think i found the issue, when escaping values in JSON i'm escaping the slash `/` which shouldn't :(
Fix is coming today.

**Comment by qetza** [comment]
Fix is released 😄
