### ISSUE TITLE
Strange Replacement of "true" with "***"

### ISSUE THREAD

**Issue by andmig-ilty** [qetza/vsts-replacetokens-task#139]
We are experiencing a weird issue today. The files after replacement of variables are corrupted by "***" replacing all the occurences of the test "true". This happens regardles the fact that the "true" value is provided by a variable or pre-exising in the file. Eg.

Replaced via variable substitution
2020-03-31T10:39:33.3799148Z           whitelist:
2020-03-31T10:39:33.3799724Z             login: false
2020-03-31T10:39:33.3800541Z             reinboarding: ***

or pre-existing in the file
2020-03-31T10:39:33.3831426Z   annotations:
2020-03-31T10:39:33.3832057Z     service.beta.kubernetes.io/azure-load-balancer-internal: "***"

**Comment by andmig-ilty** [comment]
Appartently this is a behavior of Azure Devops itself. For some reason hide some data… The files where we applied the variable replace are actaually OK… sorry for bothering...

**Comment by qetza** [comment]
Hi @andmig-ilty,
Yes this is a feature of Azure DevOps which replace all secret variable values in the logs with `***` to avoid leaking secrets.
In your case you must have a secret variable with the value `true`
