### ISSUE TITLE
Using token prefix and token suffix with spaces

### ISSUE THREAD

**Issue by GeorgyRezchikov** [qetza/vsts-replacetokens-task#143]
The utility cannot find tokens in the format {{ variable }}

Please add the ability to specify spaces in tokens.

**Comment by qetza** [comment]
Hi @GeorgyRezchikov,

Just to be clear you would like your token prefix to be `{{_` and suffix `_}}` where `_` is a space?

**Comment by GeorgyRezchikov** [comment]
Yes

![image](https://user-images.githubusercontent.com/28917934/79005248-199c3a80-7b5f-11ea-8869-750055f55c42.png)

**Comment by qetza** [comment]
Thanks.
Instead of having to put spaces in the token prefix/suffix i will make it so that spaces are ignored between the token prefix/suffix and the variable name.

**Comment by GeorgyRezchikov** [comment]
Thanks! I will wait for the new version!

**Comment by qetza** [comment]
Feature s implemented but i will release the new version middle of next week.

**Comment by techiechap** [comment]
Hi I am not sure if its relates to the issue, variables in the format __ & __  no more working

**Comment by qetza** [comment]
Hi @techiechap,
The version with the new feature on ignoring spaces is not yet released.
Could you open another issue and if possible include a diagnostic log so that i can see your configuration?
Because the only recent change was a bug fix on json value escaping.

**Comment by techiechap** [comment]
Thank you @qetza  I have opened [issue  here ](https://github.com/qetza/vsts-replacetokens-task/issues/146url), 

I used replace token  task  to replace variables in the `__ & __ format`

**Comment by qetza** [comment]
Closing issue as feature is implemented and released
