### ISSUE TITLE
Using backslash as prefix and suffix

### ISSUE THREAD

**Issue by elhitch40** [qetza/vsts-replacetokens-task#151]
I have numerous files with "Dev" references in a fileshare:
Example:  ...\ETL\ETL Data\DEV\...

I need to replace "DEV" to "STG" and "PRD" for staging and production

I'm trying to use a backslash as the Prefix and Suffix.

I have 2 variables:
Variable: DEV, Value: STG, Release: Staging
Variable: DEV, Value: PRD, Release: Production 

The result should be:
Staging:   ...\ETL\ETL Data\STG\...
Production: ...\ETL\ETL Data\PRD\...

However, I get a "name not supplied" error.

So, can you use backslashes as a prefix/suffix?  I tried escaping:  \\ and "\"

**Comment by qetza** [comment]
Hi @elhitch40,
You can use `\` as a token prefix and/or suffix but as those a characters with a meaning in your file and not use exclusively as token prefix and suffix the task may find lots of "tokens" which are not tokens.

For example with a file containing `\ETL\ETL Data\DEV\Folder` the task will try to find a variable `ETL` (first occurrence of a name between two `\`) and a variable `DEV` (second occurrence of a name between two `\`)

If you cannot change the file to include exclusive token prefix and suffix, then try to workaround by specifying a bigger prefix and suffix (for example `ETL Data\` and `\Folder`)

**Comment by elhitch40** [comment]
Thanks for the response.  I used \ETL Data\ and \Folder\ and it worked.
