### ISSUE TITLE
Variables not found - created with ##vso[task.setvariable variable=

### ISSUE THREAD

**Issue by bjtukker** [qetza/vsts-replacetokens-task#155]
Hi,

We are having issues with the replacement of variables that are filled dynamically during the release.  This happens within the same job in the pipeline. These variables, however, are not found in the replace token task. 

E.g. step 5 (bash script)
batchUrl=$(az batch account show --name $(batchAccount) --resource-group $(resourceGroupName) --output tsv --query accountEndpoint)
echo "##vso[task.setvariable variable=batchUrl;isOutput=true]$batchUrl"

In the log it is visible that the variable is filled correctly, but gives an error in the log:

log step 6
##[debug]batchUrl=undefined
##[warning]  variable not found: batchUrl
##[debug]Processed: ##vso[task.issue type=warning;]  variable not found: batchUrl
##[debug]  batchUrl: 

Is this something that can be fixed and how?

**Comment by jdkemme** [comment]
adding isOutput=true makes the variable accessible as "Step5stepname.batchUrl", which will not match the 'batchUrl' variable token replacement is looking for.  If you do not intend sharing that variable across jobs, you should remove the isOutput parameter.

**Comment by qetza** [comment]
@bjtukker,
@jdkemme is correct adding the `isOutput` will automatically prefix your variable name so that it is available in other jobs. So either remove the `isOutput` if you don't need the variable in another job or rename your token.

@jdkemme, thanks for answering :smile:

**Comment by bjtukker** [comment]
Thanks @jdkemme and @qetza for clarifying this. I copied too much for other places... 
This is fixed!
