### ISSUE TITLE
Does it work for TFS on prem?

### ISSUE THREAD

**Issue by Andreiaotto** [qetza/vsts-replacetokens-task#16]
I downloaded and tried to install it in TFS 2015.2, but I am getting na error that this extension is not installed on any currently installed products.
Error log
7/20/2016 7:19:03 AM - Microsoft VSIX Installer
7/20/2016 7:19:03 AM - -------------------------------------------
7/20/2016 7:19:03 AM - Initializing Install...
7/20/2016 7:19:04 AM - Extension Details...
7/20/2016 7:19:04 AM - 	Identifier         : replacetokens
7/20/2016 7:19:04 AM - 	Name               : Replace Tokens
7/20/2016 7:19:04 AM - 	Author             : qetza
7/20/2016 7:19:04 AM - 	Version            : 1.3.0
7/20/2016 7:19:04 AM - 	Description        : Task to replace tokens in files.
7/20/2016 7:19:04 AM - 	Locale             : en-US
7/20/2016 7:19:04 AM - 	MoreInfoURL        : 
7/20/2016 7:19:04 AM - 	InstalledByMSI     : False
7/20/2016 7:19:04 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
7/20/2016 7:19:04 AM - 
7/20/2016 7:19:04 AM - 	SignatureState     : Unsigned
7/20/2016 7:19:04 AM - 	Supported Products : 
7/20/2016 7:19:04 AM - 		Microsoft.VisualStudio.Services
7/20/2016 7:19:04 AM - 			Version : 
7/20/2016 7:19:04 AM - 
7/20/2016 7:19:04 AM - 	References         : 
7/20/2016 7:19:04 AM - Signature Details...
7/20/2016 7:19:04 AM - 	Extension is not signed.
7/20/2016 7:19:04 AM - 
7/20/2016 7:19:04 AM - Searching for applicable products...
7/20/2016 7:19:04 AM - Found installed product - Microsoft Visual Studio Enterprise 2015
7/20/2016 7:19:04 AM - Found installed product - Microsoft Visual Studio Professional 2015
7/20/2016 7:19:04 AM - Found installed product - Microsoft Visual Studio Community 2015
7/20/2016 7:19:04 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
7/20/2016 7:19:04 AM - Found installed product - Global Location
7/20/2016 7:19:04 AM - Found installed product - ssms
7/20/2016 7:19:04 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by qetza** [comment]
Hi @Andreiaotto,
To be honest i didn't do any tests on TFS on-prem as extensions weren't supported at the time i published it.
I'll try to test on TFS on-prem and make the task working.

Thanks for reporting the issue.

**Comment by Andreiaotto** [comment]
Great @qetza , thank you for answering and looking forward to have it.
I´ll look for how to do it and if I can, I let you know.

Thank you,
Andreia

**Comment by qetza** [comment]
Hi Andreia,
I've tested the installation on a TFS 2015.2.1 with the latest version (1.3.1) and it's working.

Did you follow the instructions give when clicking download on the marketplace?
- Navigate to the Team Foundation Server Extensions page on your server.
(For example, http://someserver:8080/tfs/_gallery/manage)
- Click Upload new extension and select the file you have just downloaded.
- After the extension has successfully uploaded, click Install and select the Team Project Collection to install into.

**Comment by mikaelkrief** [comment]
for me this extension work fine in TFS 2015 Update 3

**Comment by Andreiaotto** [comment]
Sorry for the late reply, yes it worked fine when I updated to TFS 2015.3.

Thank you,
Andreia

**Comment by qetza** [comment]
Hi @Andreiaotto, glad you have your issue resolved.
I'll close the issue on github then.
