### ISSUE TITLE
Any way to fail the task if no tokens are found?

### ISSUE THREAD

**Issue by jjgriff93** [qetza/vsts-replacetokens-task#160]
Hello - firstly thank you so much for writing such a useful extension

I'm trying to implement a token replace step that may, if the code is not correctly outputted in some previous steps, not produce valid tokens to be replaced. If that happens, currently the replace token step passes as it doesn't find any tokens to replace. 

Is there any way to make it fail if it detects nothing to replace?

Thanks in advance for your help!

**Comment by qetza** [comment]
Hi @jjgriff93,
You can set the missing variable action to `fail`, this will make the task fail if any token cannot be mapped to a variable.

**Comment by jjgriff93** [comment]
Thanks @qetza - I've got that set to `fail` already and works nicely when there are tokens detected but no variable to match - however in my case there are sometimes no tokens detected when there should be, so was hoping there's some equivalent `noTokensDetectedAction`?

**Comment by qetza** [comment]
@jjgriff93,
I could add an output variable to the task which would contains a json serialized summary of the task (files parsed, number of tokens found, replaced...). You could then in your pipeline add a script task to read this variable and do all the tests you want.
Would this answer your need?

**Comment by jjgriff93** [comment]
Hey @qetza thanks for getting back to me - that would be a great solution and make it flexible for reporting outputs etc. If this isn't too much trouble to add it would be greatly appreciated!

**Comment by qetza** [comment]
Hi @jjgriff93,
Version 3.7.0 of the task is released and now exposes the following output variables:
- **tokenReplacedCount**: the total number of tokens which were replaced by a variable.
- **tokenFoundCount**: the total number of of tokens which were found.
- **fileProcessedCount**: the total number of files which were processed.
- **transformExecutedCount**: the total number of transformations which were executed.
- **defaultValueCount**: the total number of default value used.

You can use those variables in a script task to do you custom logic for fail or pass.

**Comment by jjgriff93** [comment]
Amazing, thanks @qetza this will be incredibly useful

**Comment by qetza** [comment]
Hi @jjgriff93,
Sorry i had to rollback the feature as it seems that output variables are not compatible with all TFS/Azure DevOps versions. I will prepare a new major version including this feature so that users will have to optin on the version, i hope to release it this week or next week (i want to add feature which is also a breaking change)

**Comment by qetza** [comment]
Hi @jjgriff93,
I released a new version of task in preview with the output variables feature. You will need to explicitly select this version (4.x) and make sure to look at breaking changes in the release notes.
