### ISSUE TITLE
Confused about how token values are defined

### ISSUE THREAD

**Issue by jlgrau** [qetza/vsts-replacetokens-task#161]
Hello

I am trying to use your extension but I cannot make it work.

My objective is to replace in an xml file the value of the <Version> tag

?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <Version>111</Version>
  </PropertyGroup>
</Project>

So I have configured the task as follows:
steps:
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace version in AssemblyInfo files'
  inputs:
    targetFiles: '**/AssemblyInfo.csproj.xml'
    keepToken: true
    tokenPrefix: '<Version>'
    tokenSuffix: '</Version>'
    enableTelemetry: false

And I have the followings logs:
replacing tokens in: /home/vsts/work/1/s/ContractTemplateWebAPI/AssemblyInfo.csproj.xml
##[warning]  variable not found: 111
  0 tokens replaced out of 1

My question is how do a set the value to replace my token which is 111 ?

**Comment by qetza** [comment]
Hi @jlgrau,
Sorry for the late reply.

Could you repost your example using the markdown to make sure it is displayed as XML (` ```xml ... ``` `) as i cannot see it.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
