### ISSUE TITLE
Wrong fallback of environment variables in Azure Release 

### ISSUE THREAD

**Issue by brunobertechini** [qetza/vsts-replacetokens-task#162]
Scenario: Azure Release pipeline (not yaml).

In Azure Release pipelines you can set variables in the scope of the environment. Like Staging/Development/Production etc.

Here is my scenario:

Environment Development has a variable VAR1 defined and set to FOO.
Environment Staging DOES NOT have a variable VAR1 defined at all.

When I use the replace task in the Staging environment, it is using the value of VAR1 and populating the value from the wrong environment (Development) and setting the value to FOO.

This should not happen. My expectation would be : (if we have the Action set too "fail") the task should fail for environment Staging as it does not have the variable defined. 

This "fallback" method is really dangerous.

Note: If I have the variable defined in both environments (with different values) it is working fine!

I think this is a critical bug and might cause unexpected behavior if you define one variable for a Production environment and forget to define the same variable for other environments

**Comment by qetza** [comment]
Hi @brunobertechini,
The task has no notion of environment or fallback, it just has access to a list of variables provided by the agent.

Based on what you say you should open an issue in the azure devops agent project: https://github.com/microsoft/azure-pipelines-agent

**Comment by brunobertechini** [comment]
Hi @qetza , It actually does because if I use this task under Releases (not in yaml) we have all the environments and variables are defined under the scope of those environments.

I just wanted to highlight that this might break some pipeline implementations for those who use this task under Releases like I do.

I will try to debug and see if it's something related to azure itself. I don't remember seeing the variables from another environment within the agent.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
