### ISSUE TITLE
Very large file is truncated

### ISSUE THREAD

**Issue by graphicsxp** [qetza/vsts-replacetokens-task#164]
I'm using the task to tokenize a minified javascript file, which is the output of an Angular build.

the file is just over 1 Mb large. The token is found and replaced correctly, but then when the file is saved on disk, it gets truncated and is only 400kb

This is the file I want to tokenize;  https://1drv.ms/u/s!Ai7himO_T6ekhZUS9DKUv7ZulMm-qg?e=9iKk9N

Is it possible to fix this issue ?

**Comment by qetza** [comment]
Hi @graphicsxp,
Thanks for sharing the issue and your file. I will investigate and try to fix this.

**Comment by graphicsxp** [comment]
Hi @qetza, did you figure it out ? 
Also, I have a question so I may just as well ask it here:  the replace token task replaces token in release variables. But does it work with variables from variable groups ?

**Comment by graphicsxp** [comment]
Hello, is there any progress on this issue ?

**Comment by qetza** [comment]
Hi @graphicsxp,
Sorry for the really late reply. I've tried to reproduce the issue by just reading your file and rewriting it but the output is identical. If you still have the issue could you share the following info:
- original file
- output file
- your task parameters
- task logs

Thanks

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
