### ISSUE TITLE
Token replacement in yaml files

### ISSUE THREAD

**Issue by lockdrew** [qetza/vsts-replacetokens-task#165]
Hi, 

Apologies, but this is more of a question - Does this task work to replace secrets in a yaml file. 
We use helm and I'd like to replace some environmental variables in my chart as part of my build pipeline. It seems to be finding the file, but not replacing the values in the file. 

Thanks,
Drew

**Comment by qetza** [comment]
Hi @lockdrew,
Sorry for the late reply, yes the task works on any text file. If no tokens are replaced then the task could not find any token based on the regex created using the token prefix and suffix specified as parameters.
Could you share your diagnostic logs and maybe a sample input file?
Thanks

**Comment by aadesola** [comment]
Hello @qetza, I have a similar challenge. I used the default prefix and suffix (#{    }#) and a sample token in my YAML looks like

 KEY:  "VALUE"
 KEY:  "VALUE"
 KEY:  "VALUE"
 KEY:  "VALUE"
 KEY:  "VALUE"

**Comment by qetza** [comment]
Hi @aadesola,
Here is an example of a tokenized yaml file:
```yaml
key1: "#{mykey1}#"
obj1:
- key1: "#{obj1.mykey1}#"
```
You then have to declare the following variables:
- `mykey1`
- `obj1.mykey1`

**Comment by aadesola** [comment]
@qetza , thanks a lot for your response. It works!!!
