### ISSUE TITLE
Recursive nested replacement

### ISSUE THREAD

**Issue by vtermaat** [qetza/vsts-replacetokens-task#167]
Is there an options to recursively replace nested tokens?
fe: #{const-#{variable}#-const}#

**Comment by qetza** [comment]
Hi @vtermaat,
Sorry for the late reply, no there is no option to do recursive replacements and i'm not sure this could be done.
If you know the level of recursion you want you could try calling the task multiple time using different token prefixes and suffixes for each call:
- your file: `{{const-#{variable}#--const}}`
- first call with `#{`, `}#` as prefix/suffix would output `{{const-myvalue-const}}`
- second call with `{{`, `}}` as prefix suffix would output `myothervalue`

**Comment by qetza** [comment]
Closing for long inactivity and request for recursive replacement will be linked to issue #201
