### ISSUE TITLE
TFS 2017.2 plugin install non ending

### ISSUE THREAD

**Issue by carloreggiani** [qetza/vsts-replacetokens-task#168]
Hi
I'm trying to install the extension version 3.6.0 (qetza.replacetokens-3.6.0.vsix) on out TFS Server 2017.2 but the loading process not end... any compatibility issue?

Thanks
Carlo

**Comment by qetza** [comment]
Hi @carloreggiani,
Sorry for the late reply, I do not know of any compatibility issue with TFS 2017.2. I haven't changed the requirements since v2.0.0 which removed compatibility with TFS 2015.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
