### ISSUE TITLE
Replace token

### ISSUE THREAD

**Issue by Stephenraj592** [qetza/vsts-replacetokens-task#173]
How to use Replace token in order to change the following image name in YAML file

**image: xyz.azurecr.io/abc-v0:latest** 

Eg. I need to change the version from v0 to v1

**Comment by qetza** [comment]
Hi @Stephenraj592,
You could tokenize the version like this `image: xyz.azurec.io/abc-#{version}#:latest` then add a variable in your pipeline (our variable group) with the name `version` and the value `v1`.
If you cannot tokenize the file then you could customize the token prefix and suffix to target your specific line:
- token prefix `image: xyz.azurecr.io/abc-`
- token suffix `:latest`
- variable name `v0`
- variable value `v1`

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
