### ISSUE TITLE
Release variables with empty values cannot be found when replacing via task

### ISSUE THREAD

**Issue by JakeRoper4** [qetza/vsts-replacetokens-task#174]
Hello,

Feel free to respond and close this if this has been answered already, but I'm currently experiencing an issue with Azure Devops and passing through release variables.

For example, I have the below variable set within my release pipeline:

![image](https://user-images.githubusercontent.com/54897068/92391967-73f0f580-f115-11ea-9072-55e82c1d441c.png)

This variable will essentially emulate an empty value for a key/value pair in JSON:

```
"ApplicationInsights": {
     "InstrumentationKey": ""
}
```

Crux of the issue is, that when I run a release within the variables set above, when it comes to the replacing of the variables via the task, it displays the error of:

![image](https://user-images.githubusercontent.com/54897068/92394595-bae0ea00-f119-11ea-97a3-6c3d077bccce.png)

Though I can see the variable within the list of env variables within the release:

![image](https://user-images.githubusercontent.com/54897068/92394917-5c683b80-f11a-11ea-95c0-199d9deec476.png)

Anything that I'm missing with the configuration of the task?

**Comment by qetza** [comment]
Hi @JakeRoper4,
Replacing with an empty value is special as the task needs to differentiate between an actual empty value and a non existing variable (the sdk returns an empty value if the variable doesn't exists).
To manage this you can set the value of your variable to `(empty)`, this will be replaced by an empty value by the task. You can change the empty token using the task parameter `Empty value` in the `Advanced` section.

**Comment by JakeRoper4** [comment]
Hi @qetza - Thank you for the quick reply! So you're saying that even though the variable is created within the release pipeline, with an empty value, the task won't pick it up due to limitations from an sdk? In my scenario posted above, I should be able to set the variable in the pipeline to `(empty)`, from which the task can then replace this value with `""`?

**Comment by qetza** [comment]
Hi @JakeRoper4,
Yes you are correct limitation in the sdk made me add this "empty value token". Setting your variable to `(empty)` will replace in your file the token with an empty string.

**Comment by padillah** [comment]
There appears to be a difference between (empty) and ''. I'm deploying a service fabric cluster and if I use (empty) the code deployment fails with the error "One or more placement constraints on the service are undefined on all nodes that are currently up."

If I use '' the code will deploy fine.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
