### ISSUE TITLE
Allow YAML as Variable File format

### ISSUE THREAD

**Issue by kchri-nets** [qetza/vsts-replacetokens-task#177]
Please add the possibility to use Yaml as Variable File Format

**Comment by qetza** [comment]
Hi @kchri-nets,
Do you means support YAML in the `Escape values type` parameter list?

**Comment by qetza** [comment]
Hi @kchri-nets,
Version 3.7.0 of the task is released and now supports variable files in YAML. Those files must have the extension `.yml`or `.yaml` to be parsed as YAML.
