### ISSUE TITLE
Set a default value, if a token is found, but the variable is not present

### ISSUE THREAD

**Issue by ClemensSutor** [qetza/vsts-replacetokens-task#179]
Hello Guillaume,

If a variable is not present/not set in the actual Azure Devops pipeline context, the extension inserts an empty string.

I want to the extension to be able to set a given default value, if a token is found in the files to be tokenized, but the variable is not present.
 
Why is this needed?
The actual behavoir of the extension  can cause problems with some programs/wep apps, because they are not expecting a value in the config files to be an empty string.
For me, some Wep Apps based on older .NET Framework versions are failing to start, because some 'appsetting' keys are emty in the web.config. The build in configuration manager is trying to load all values on startup, and fails. I can't change this behavoir easily.

I created a pull request for this, with a working  solution.

Pull Request:
https://github.com/qetza/vsts-replacetokens-task/pull/178

Bye
Clemens

**Comment by qetza** [comment]
Hi @ClemensSutor,
Thanks i'll review your PR.

**Comment by qetza** [comment]
Hi @ClemensSutor,
Your feature is now released with version 3.7.0 :smile:
I've done a small refactor to expose only a single parameter `Default value`, if the parameter is empty the task works as previous but if a value is setted then this will be used when no variable is found and the other features will be run on this default value (transformations...)

**Comment by ClemensSutor** [comment]
Hello Guillaume,

thanks for integrating this feature into the extension :)

Bye
Clemens
