### ISSUE TITLE
Array Token

### ISSUE THREAD

**Issue by dorin182** [qetza/vsts-replacetokens-task#180]
Hi, I've got an issue with the array token.

The configure file:
``` 
"obj":[#{myVariable}]
```
The variable value is:
``` 
"test","test2","test3"
```

the result of token replacement I get the following:
``` 
"obj":[\"test\",\"test2\",\"test3\"]
```
but the expected result should be the following:
```
"obj":["test","test2","test3"]
```

I know I could define each value by dot and number/index of the array but unfortunately, each release has a different number of values in the array. For example, one release has 2 values in array but others could have more than 4 and by the time is necessary to add more or to reduce.

**Comment by qetza** [comment]
Hi @dorin182,
This is because the task treats all variables as text and as your file is json will by default automatically escape characters in your variables.
You can disable this by setting the parameter `Escape values type` to `no escaping`but this will apply to all variables.

**Comment by dorin182** [comment]
> Hi @dorin182,
> This is because the task treats all variables as text and as your file is json will by default automatically escape characters in your variables.
> You can disable this by setting the parameter `Escape values type` to `no escaping`but this will apply to all variables.

thank you, everything works fine
