### ISSUE TITLE
May i know what data will be sent to the "task author" if " enableTelemetry" option enabled? Who is the "Task author"? Is there any way that we can restrict the user to change the setting of this

### ISSUE THREAD

**Issue by fongkisz** [qetza/vsts-replacetokens-task#181]
We wanted to use this plugin badly, but the concern we have is around the topic of security and privacy.

**Comment by qetza** [comment]
Hi @fongkisz,
Please find below the answer to your questions. (i will update the readme on next release with those details).

**Who is the task author?**
It's me :smile: (https://github.com/qetza)
More precisely, all the telemetry data are sent to an instance of Azure Application Insights that i am the only one with access too.

**Is there any way that we can restrict the user to change the setting of this?**
Not sure i understand your question. If you mean "can you force the setting to be disabled and be sure that no developer can enable it" then what you can do is set on all your build servers an environment variable `REPLACETOKENS_DISABLE_TELEMETRY` with the value `true` this will always disable telemetry. If you cannot set environment variables then you could use a pipeline decorator (https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops) to inject a step which adds variable with the same name and value.

**May i know what data will be sent?**
Here is the list of data sent (no personal data):
- The hash (SHA256) of your collection id (this is an internal GUID)
- The hash (SHA265) of your project id (this is an internal GUID) and build definition id (this is an internal integer)
- The pipeline type (release, or build)
- The server type (server or services)
- The value of the parameter `Action`
- The value of the parameter `Characters to escape`
- The value of the parameter `Empty value`
- The value of the parameter `Files encoding`
- The value of the parameter `Escape character`
- The value of the parameter `Escape values type`
- The value of the parameter `Keep token`
- The regex pattern used to find tokens (this is based on the parameters `Token prefix` and `Token suffix`)
- The result of the task (succeeded of failed)
- The number of rules to find files (this is the number of patterns in the parameter `Target files`)
- The number of rules using wildcard (this based on the parameter `Target files`)
- The number of rules using negative pattern(this based on the parameter `Target files`)
- The number of rules using the output (this based on the parameter `Target files`)
- The value of the parameter `Token prefix`
- The value of the parameter `Token suffix`
- The number of variables found in the variable files (this is based on the parameter `Variable files (JSON)`)
- The value of the parameter `Variable separator`
- The value of the parameter `Verbosity`
- The value of the parameter `Write unicode BOM`
- The value of the parameter `Use legacy pattern`
- The duration of the task execution
- The number of token replaced
- The number of tokens found
- The number of files processed

**Comment by qetza** [comment]
I'm archiving the project and moving it to a new repository https://github.com/qetza/replacetokens-task
