### ISSUE TITLE
Unable to select task version 3

### ISSUE THREAD

**Issue by alancantekin** [qetza/vsts-replacetokens-task#182]
Hi,
I was about to release my project in Azure DevOps when this error got in the way: "**Could not find files with glob [Roche.Rok.WebApps3.WebApplication.CalendarExplorer.SetParameters.xml].**"
The replace tokens look like this:
![image](https://user-images.githubusercontent.com/64463505/104316228-722ca980-54dc-11eb-9f8d-c98c693412f3.png)

It's also a bit suspicious that on the successful build under "Publish Artifact: drop" only 4 files are uploaded. There should actually be more.
![image](https://user-images.githubusercontent.com/64463505/104316433-bddf5300-54dc-11eb-9cb8-c4f7039eb5f6.png)

How can I fix this error?

Thanks in advance.

**Comment by qetza** [comment]
Hi @alancantekin,
Version 1 is a really old version not supported anymore.
If you are on Azure DevOps you should be able to select a newer version. Maybe you can contact the admin of your account to check the installed extensions and see if there is something there.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
