### ISSUE TITLE
Replace objects in json

### ISSUE THREAD

**Issue by chr0m1ng** [qetza/vsts-replacetokens-task#183]
Hi, I'm trying to use the Replace Tokens task to replace a variable in a `json` file, but the value must be an `object`, i.e. an `array` or `dictionary`.

The file:
```json
{
    "key": {
        "foo": "bar",
        "uuu": "aaaa"
    },
    "otherKey": [1, 2, 3]
}
```

The defined variables/secrets:
|name| value|
|---|---|
|key|{"foo": "batata", "uuu": "iiii"}|
|otherKey|["a", "b", "c"]|

But the values are always escaped when replaced.

This works fine using the File Transform task as [docs show here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops&tabs=Classic#json-variable-substitution-notes)

**Comment by qetza** [comment]
Hi @chr0m1ng,
This is because the task will by default escape characters in your values as it a JSON file.
You can disable character escaping by setting the value of the parameter Escape values type to `no escapeˋ

**Comment by qetza** [comment]
Hi @chr0m1ng,
I've will soon release the version 3.7.0 of the task which will support some transformations on the variable values. One of the transformation is `noescape` which will disable escaping for the token while maintaining escaping for other tokens.

So you could have your file like this:
```
{
  "key": #{unescape(key)}#,
  "otherkey": #{unescape(otherkey)}#,
  "string": "#{string}"
}
```

And the variables:
| name | value |
| -- | -- |
| key | {"foo": "batata", "uuu": "iiii"} |
| otherkey | ["a", "b", "c"] |
| string | a string needing "escape" |

This will produce the file:
```
{
  "key": {"foo": "batata", "uuu": "iiii"},
  "otherkey": ["a", "b", "c"],
  "string": "a string needing \"escape\""
}
```

**Comment by chr0m1ng** [comment]
> Hi @chr0m1ng,
> I've will soon release the version 3.7.0 of the task which will support some transformations on the variable values. One of the transformation is `noescape` which will disable escaping for the token while maintaining escaping for other tokens.
> 
> So you could have your file like this:
> 
> ```
> {
>   "key": #{unescape(key)}#,
>   "otherkey": #{unescape(otherkey)}#,
>   "string": "#{string}"
> }
> ```
> 
> And the variables:
> 
> name	value
> key	{"foo": "batata", "uuu": "iiii"}
> otherkey	["a", "b", "c"]
> string	a string needing "escape"
> This will produce the file:
> 
> ```
> {
>   "key": {"foo": "batata", "uuu": "iiii"},
>   "otherkey": ["a", "b", "c"],
>   "string": "a string needing \"escape\""
> }
> ```

Nice! I can't wait to use it, will help me a lot. Thanks for your return

**Comment by qetza** [comment]
Hi @chr0m1ng,
Version 3.7.0 of the task is released, you can now use the `noescape` transformation (be sure to activate it in the advance settings).

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
