### ISSUE TITLE
[Question] How to add YAML variable blocks?

### ISSUE THREAD

**Issue by flmmartins** [qetza/vsts-replacetokens-task#187]
Is it possible to add YAML blocks?

For example let say:

### My variables:

**rule_1** 

```bash
- host: mydns.com
    http:
      paths:
       - backend:
          serviceName: mySvc1
          servicePort: 80
```

**rule_2**

```bash
- host: mydns2.com
    http:
      paths:
       - backend:
          serviceName: mySvc2
          servicePort: 80
```

### File:
```bash
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  name: __app__
spec:
  rules:
  __rule_1__
 __rule_2__
```

Is there any way to accomplish this? Have more elaborate variables instead of strings?

**Comment by qetza** [comment]
Hi @flmmartins,
As you cannot set new lines in variable values directly the workaround is the following:
- in your variable values use a variable when you need to insert a new line:
```
rule_1 = - host: mydns.com$(NewLine)    http:$(NewLine)      paths:$(NewLine)        - backend:$(NewLine)          serviceName: mySvc1$(NewLine)          servicePort: 80
```
- add in your job at the top a script task to create a this variable containing the new line character(s):
```
- pwsh: write-host "##vso[task.setvariable variable=NewLine]%0D%0A"
```
- add the replace token task.

This will effectively inject the variable value with new line characters in the file.

**Comment by flmmartins** [comment]
Tks @qetza !
