### ISSUE TITLE
Allow for run on remote machine

### ISSUE THREAD

**Issue by greyknight79** [qetza/vsts-replacetokens-task#189]
We don't have agents on every machine we deploy to. Those machines without agents on them have files and powershell scripts run on them remotely from a machine that has an agent on it. If could allow for a similar behavior of being able to specify a remote machine to run the step on that would be very convenient.

**Comment by qetza** [comment]
Hi @greyknight79,
I think the other task are using native functions to run scripts/commands remotely (like ssh, or remote powershell). But the replace token task is just a node script which needs to run on the agent as it is depend of the agent sdk lib.

One workaround you could use is:
- to have your files with tokens on the agent
- run the replace tokens task on those file
- copy the file on the remote machine
- delete files locally
- run your script remotely

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
