### ISSUE TITLE
Evaluating environment variables

### ISSUE THREAD

**Issue by dzimmyman** [qetza/vsts-replacetokens-task#19]
Is there a trick to get it to evaluate TFS build or release variables?  For example: 

tokenPrefix = __
tokenSuffix = __
regex: __((?:(?!__).)*)__
Replacing tokens in file '...index.html'...
Replacing '__Version__' with '$(Release.ReleaseId)'

token __Version__ 
gets replaced with the literal $(Release.ReleaseId) rather than the value of that variable.

**Comment by qetza** [comment]
Hi @dzimmyman,
The task is not currently expanding predefined variables, i'll add this to the backlog.
As a workaround you can use the `Expand Variables` task from the marketplace extension `Variable Toolbox` as your first step, this will do the variable expansion.

**Comment by dzimmyman** [comment]
Interesting.  (https://marketplace.visualstudio.com/items?itemName=jessehouwing.jessehouwing-vsts-variable-tasks)  Have you tried that?  Then all subsequent tasks will have the variables auto-expanded in subsequent tasks by just referencing $(Release.ReleaseID)?  I need to check out the slight-of-hand there.  It must be overloading the variable with the expanded value somehow.  I didn't realize you could do this.  Thanks for the tip and shared task!

**Comment by qetza** [comment]
I've added the variable expansion to the replace tokens task.

If you want global expansion use the `Expand Variables` task from @jessehouwing at the start of your process, it will expand all variables and update their value for subsequent tasks.

**Comment by qetza** [comment]
Hi @dzimmyman,
Just to let you now that the new xplat agent is automatically doing variables expansion. If you want to switch to this version the `Replace Tokens` task is now compatible with release 1.4.1.
