### ISSUE TITLE
Webdeploy package integration

### ISSUE THREAD

**Issue by selhoum** [qetza/vsts-replacetokens-task#2]
Guillaume,
Great idea, but I cannot make the task work with a webdeploy package that is deployed to Azure webapps.
any hints?

Thanks

**Comment by qetza** [comment]
Hi @selhoum,

For webdeploy, the configuration file is inside the package so you would have 2 options:

1. update package content before publish:
  - unzip,
  - replace tokens
  - zip
  - publish
2. use parameters.xml and setparameters.xml files:
  - define your parameters in parameters.xml
  - create a setparameters.xml file with your tokens in it
  - during deployment, replace tokens in setparameters.xml then publish using the updated setparameters.xml file

The option 2 is simpler to implement but offer less customization (you can only do what webdeploy allows to do with parameters.xml).

**Comment by patelrk** [comment]
Hi @qetza,

I tried option 1 above but that didn't work as the minute you change the package contents and zip it up, the internal hash becomes different and Azure will complain that the package is not valid.

**Comment by qetza** [comment]
Hi @patelrk,

Thanks for the feedback. As i don't like webdeploy (and i hate Microsoft for forcing us to use it for Azure...) i don't use it a lot.

Base on your feedback it means that you would have to recreate the package using msdeploy command line (https://technet.microsoft.com/en-us/library/dd569106(v=ws.10).aspx). I this cas i would change the build to just deliver the files as is and a deployment time, update the configuration files, create the webdeploy package and publish.

**Comment by patelrk** [comment]
Hi @qetza

Thanks for the link.  I agree, Microsoft has made this much harder than it needed to be when deploying  to Azure.  I understand now how to go about this. I also found this link quite useful : https://iainhunter.wordpress.com/2011/08/31/automating-azure-1-4-packaging-using-msbuild-and-cspack/

**Comment by qetza** [comment]
If no more comment i'll close this issue.
