### ISSUE TITLE
Task Groups don't appear to be supported

### ISSUE THREAD

**Issue by samrueby** [qetza/vsts-replacetokens-task#200]
I have this task defined in a Task Group. This Task Group has input parameters, however this task is somehow unable to see them. It replaces tokens defined from the pipeline's 'Variable's tab, but Task Group Input Parameters are ignored.

**Comment by qetza** [comment]
Hi @samrueby,
Task group parameters are not variables, those are just "string tokens" which are replaced with the value during preprocessing of the pipeline so they are not visible to any task.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
