### ISSUE TITLE
Is there a way that I can replace tokens in zip file

### ISSUE THREAD

**Issue by spothamshetty** [qetza/vsts-replacetokens-task#203]
I have appSettings.json file which got zipped and is inside a zip fille. can I replace tokens in json file using this Task.

**Comment by qetza** [comment]
Hi @spothamshetty,
The task doesn't look in archive files as they are many formats. What you can do is have a task to unzip your archive, then do the replace and at the end another task to zip back the files.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
