### ISSUE TITLE
Variable separator is not working

### ISSUE THREAD

**Issue by harsha-swamy-ms** [qetza/vsts-replacetokens-task#206]
We have appsettings.json with an array declaration. 
`{
    "allowedValues": []
}`

 The vars.json file contains the values declared as below:
`
"allowedValues.0" : "guid1".
"allowedValues.1" : "guid1".
`

The varable separator value is set to : .

The replacetokens task is not updating the allowedValues in appsettings.json.

I tried removing the empty array declaration in appsettings.json assuming that the array will be added, but that also didn't work. 

Is the above usage correct?

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
