### ISSUE TITLE
The task succeeds when target file is undefined

### ISSUE THREAD

**Issue by ilonaChodnicka** [qetza/vsts-replacetokens-task#210]
Hello again, Guillaume

I forgot to define a pipeline variable that points to the target file that needs to have tokens replaced: 

![01](https://user-images.githubusercontent.com/66924607/119046934-4a1ded00-b98b-11eb-8081-5121a23273d7.jpg)

Then the replace tokens task did not throw any errors: 
![03](https://user-images.githubusercontent.com/66924607/119047258-a97bfd00-b98b-11eb-80d6-c05374c5632d.jpg)

I expect the task to throw an error if it can't find the target(s) file(s), even when that target(s) file(s) name(s) is/are not defined.

**Comment by ilonaChodnicka** [comment]
Additional comment - I made TWO mistakes in the task's input values that were not caught by the task:

1. Root directory path did not exist 

Root directory was set to $(System.DefaultWorkingDirectory)/VC-VCViolationExtractor-CI/drop/VCViolationExtractor/ScheduledTaskDefinition instead of $(System.DefaultWorkingDirectory)/VC-VCViolationExtractor-CI/drop/VCViolationExtractor/ScheduledTaskDefinitions ( 's' at the end was missing ) 

2. 03_SCHEDULED_TASK_DEFINITION_FILE pipeline variable is not defined

**Comment by qetza** [comment]
Hi @ilonaChodnicka,
Currently the task is not looking at file existence to determine success or failures. As a workaround with v4 of the task you could add a script task after the replace task and check the output variable `fileProcessedCount`.

I will this issue as a feature request to have a new `On no file processed` parameter which will allow users to continue, warn or error if no file was processed.

**Comment by ilonaChodnicka** [comment]
Hello

I already added checking number of replaced tokens as sanity check.
Thank you

**Comment by bjowes** [comment]
I would need this too. I am using this task inside a template which is used multiple times within our release pipeline. This makes it impossible to access the output variables - I cannot give the replacetoken task a name since then devops complains that the name must be unique. A setting similar to `actionOnMissing`, but for input files, would be really helpful.

**Comment by qetza** [comment]
The new release now support the parameter `Action on no file processed` which can mark the task as failed if no files were found.
