### ISSUE TITLE
Incorrect ENV var to disable telemetry (mismatch beetwen code & docs)

### ISSUE THREAD

**Issue by emanuelb** [qetza/vsts-replacetokens-task#216]
In docs the env var `REPLACE_TOKENS_DISABLE_TELEMETRY` is used:
https://github.com/qetza/vsts-replacetokens-task/blob/109fc2e9e39c4aaa0b05fe763f7628fa83fb1745/ReplaceTokens/ReplaceTokensV3/README.md#datatelemetry
https://github.com/qetza/vsts-replacetokens-task/blob/109fc2e9e39c4aaa0b05fe763f7628fa83fb1745/ReplaceTokens/ReplaceTokensV4/README.md#datatelemetry
https://github.com/qetza/vsts-replacetokens-task/blob/109fc2e9e39c4aaa0b05fe763f7628fa83fb1745/README.md#datatelemetry
by setting a variable or environment variable `REPLACE_TOKENS_DISABLE_TELEMETRY` to true.

while in code env var `REPLACETOKENS_DISABLE_TELEMETRY` is used (`REPLACETOKENS` instead of `REPLACE_TOKENS`)

https://github.com/qetza/vsts-replacetokens-task/blob/0cf0fc60047701e8e40a131b6799489edb9fbefe/ReplaceTokens/ReplaceTokensV4/index.ts#L469
https://github.com/qetza/vsts-replacetokens-task/blob/109fc2e9e39c4aaa0b05fe763f7628fa83fb1745/ReplaceTokens/ReplaceTokensV3/index.ts#L469

```typescript
import tl = require('azure-pipelines-task-lib/task');
```

the function getVariable just replace `.` & ` ` with _ and uppercase the string:
https://github.com/microsoft/azure-pipelines-task-lib/blob/77c834ef3e62f9a43f28a2ef74bd517146a9da27/node/task.ts#L115
https://github.com/microsoft/azure-pipelines-task-lib/blob/77c834ef3e62f9a43f28a2ef74bd517146a9da27/node/internal.ts#L258-L264

**Comment by qetza** [comment]
Hi @emanuelb,
Thanks for reporting the issue, i've fixed the documentation :smile:
