### ISSUE TITLE
replace keyvault resource ID

### ISSUE THREAD

**Issue by fabdi00** [qetza/vsts-replacetokens-task#217]
Hi, 

Is it possible to replace keyvault id value in a param file with this?
I keep getting this:

##[error]KeyVaultParameterReferenceNotFound: The specified KeyVault '/subscriptions/111111-22222-33333-44444/resourceGroups/#rg-ado-we/providers/Microsoft.KeyVault/vaults/keyvault#' could not be found

**Comment by qetza** [comment]
Hi @fabdi00,

If your file is a text file then you should be able to do any replacement in it if you put the replace token task before the file is used.
Maybe your issue is with the token syntax? What is the output of the replace token task?

**Comment by fabdi00** [comment]
no my file was a json parameter file, I wanted to change the ID shown below

"SasToken": {
      "reference": {
        "keyVault": {
          "id": "#/subscriptions/{subs ID}/resourceGroups/rg/providers/Microsoft.KeyVault/vaults/keyvault#"
        },
        "secretName": "nSasToken"
      }

the deployment kept failing because it didn't like the hash even though the replace token task was showing it changed the value.

I just gave up and ended up using  override parameter instead as I was running out of time.

**Comment by qetza** [comment]
Hi @fabdi00,
Glad you found a workaround.

I think the issue with the replace token tasks was some miss configuration or syntax issue.
