### ISSUE TITLE
Telemetry option

### ISSUE THREAD

**Issue by andrea-cassioli-maersk** [qetza/vsts-replacetokens-task#227]
Hi,
I have just notice the `enableTelemetry` option. It is not very clear from the docs whether it is enabled or not by default. When I use the task in a scripted pipeline in ADO, it seems it is enabled (see screenshot). Could you clarify?

<img width="1283" alt="Screenshot 2021-11-08 at 10 26 46" src="https://user-images.githubusercontent.com/70192688/140716913-69915735-2f3b-4a86-8e09-92f4b419f146.png">

**Comment by qetza** [comment]
Hello @andrea-cassioli-maersk,
Yes by default telemetry is enabled. To disable it add the input `enableTelemetry: false`

**Comment by andrea-cassioli-maersk** [comment]
OK, it was not clear to me from the docs.
