### ISSUE TITLE
Deployment Task needs updating to new version of Node??

### ISSUE THREAD

**Issue by R-Lamberson** [qetza/vsts-replacetokens-task#230]
I am seeing this message in the execution logs for the replacetokens task.  Is this going to be updated soon?

##[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

**Comment by qetza** [comment]
Hi @R-Lamberson,
I'm working on migrating to node 10

**Comment by qetza** [comment]
New versions of the task are released using Node10.

**Comment by qetza** [comment]
I had to revert the change as it impacted on-premises installs and failed pipelines. I've reopen the issue #228 to follow this need

**Comment by qetza** [comment]
New version 5 of the task was released which is executing on node10. Please be award that the v5 was based on the v4 so all breaking change of v4 applies to v5.
