### ISSUE TITLE
Enhancements to the "Variable files (JSON or YAML)" parameter

### ISSUE THREAD

**Issue by tknarr-starbucks** [qetza/vsts-replacetokens-task#236]
Trying to get away from the MS file transform task, I'd realized it'd be handy to enhance the ReplaceTokens task so I could take the replacement values from variables (JSON or YAML text content) instead of files. Thinking about how to do that, being able to handle literal text (JSON or YAML) instead of a list of files or variables would also be handy and easy enough. I'd like to submit that enhancement as a PR once I've gotten it done over the holiday.

Does this sound like it'd be something that'd be accepted?

**Comment by qetza** [comment]
Hi @tknarr-starbucks,
I don't think i fully understand your feature request but i'm happy to have some PR, just make sure that is does not impact existing executions and i'll review it.

**Comment by tknarr-starbucks** [comment]
Question on the build process: the `make.js` file seems to encapsulate it, but exact usage isn't documented. I'd like to package and test the extension before I create the PR, can you give a brief run-down on your process for building and packaging the extension? Thank you.

**Comment by qetza** [comment]
Hi @tknarr-starbucks,
Yes you need to run it through node like this for building and packaging a test version:
`node make build package --version auto --stage dev`

Then you will need to publish the extension and install it as a private extension on your azure devops account.

But before doing the build and package change locally the following files:
- vss-extension.json: replace the property `id` with your own id and `publisher` with your own publisher name
- make.js: replace `options.taskId` with a new guid.

This will make sure that you build an extension which does not conflict with the official one 😄

**Comment by tknarr-starbucks** [comment]
Thanks.

**Comment by tknarr-starbucks** [comment]
Going to close this. The concept works, but since there's no way to easily create a multi-line variable in the pipeline UI it's impossible to make use of it.
