### ISSUE TITLE
replaceTokens crashing

### ISSUE THREAD

**Issue by tmandekic** [qetza/vsts-replacetokens-task#238]
In our vsts deployment pipeline, we have started getting following error suddenly since yesterday: 
##[error]A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details. 
We are using Windows Server 2019 Standard. 
Any ideas about what the issue might be?

**Comment by qetza** [comment]
Hi @tmandekic,
Please make sure that you update to the latest version of the extensions (4.2.1) containing the latest task versions (3.9.1 and 4.1.1). This should fix the issue introduced in the previous version.

**Comment by tmandekic** [comment]
That worked! Thanks!
