### ISSUE TITLE
\ replacement in json and config files

### ISSUE THREAD

**Issue by evergrn435** [qetza/vsts-replacetokens-task#239]
Hi,

I'm not sure if this is possible, but I have a variable in Azure pipelines variable group that has a value such as 'C:\Temp\Files'

I am using this variable for replacement in both json and config files. In the config file I would like the 'C:\Temp\Files' value to be inserted, but in the json, I would like 'C:\\\Temp\\\Files' inserted.

Is this possible to do somehow?

Thanks

**Comment by qetza** [comment]
Hi @evergrn435,
If your json file has the extension `.json` the task should by default escape characters. If the file doesn't have this extension, you can configure it using the parameter `Escape type` and set it to `json`.
If forced, escape will be applied for all files so you should duplicate the task, one without escape and one with escape.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
