### ISSUE TITLE
Correct usage of variable files?

### ISSUE THREAD

**Issue by LaMMMy** [qetza/vsts-replacetokens-task#240]
Hi, this is not so much an issue as it is a request for help. I have a yaml Azure pipeline as such:

`  inputs:
    rootDirectory: '$(build.artifactStagingDirectory)\CDXSubmitSend\UnZip\Bindings\\'
    targetFiles: '*.xml'
    encoding: 'auto'
    tokenPattern: 'custom'
    tokenPrefix: '__'
    tokenSuffix: '__'
    writeBOM: true
    escapeType: 'xml'
    verbosity: 'detailed'
    actionOnMissing: 'warn'
    keepToken: true
    actionOnNoFiles: 'continue'
    enableTransforms: false
    useLegacyPattern: false
    enableTelemetry: true
    variableFiles: 'PipelineVariables/dev.yml'`

the PipelineVariables/dev.yml is at the root of the DevOps repo and look like this.:

     ---   
     SubmitAddress: 'https://my.site.com/Submit.svc'

I have a SubmitAddress Pipeline variable defined, but the docs say that the files will override those (which is what I want). However, I can't seem to get the variable file to work as it always just uses the pipeline variable (which is working flawlessly). Is there something I'm doing wrong?

Also, are there any examples of what a JSON or YAML variable file should look like? I get the general syntax, but what is this task expected exactly?

Thanks.

**Comment by qetza** [comment]
Hi @LaMMMy,
I cannot reproduce the issue, the variable file is being loaded and the value from the file is used.

What do you have in the logs? As you have set verbosity to detailed you should see in the logs the variables that are loaded and the token replaced.

You can also enable system diagnostics when running the pipeline to have all debug logs.

**Comment by LaMMMy** [comment]
Hi @qetza, 

Thanks for the reply. It turns out that I didn't realize the Replace Tokens task was using the Root Directory parameter as the root for my variable files as well. I assumed (incorrectly) that it was from the default working dir.

Once I tried using the root as my root, it worked. 

Thanks a bunch.

**Comment by LaMMMy** [comment]
Used Root Directory as starting place for navigating to variable files.
