### ISSUE TITLE
variable file schema?

### ISSUE THREAD

**Issue by morten-nielsen** [qetza/vsts-replacetokens-task#242]
Are there any examples of what a JSON or YAML variable file should look like?

**Comment by qetza** [comment]
Hi @morten-nielsen,
Sorry for the late reply, there are no example right now but i will put some here:

For JSON file the simplest is just key value where values are simple types:
```json
{
  "myvar1": 1,
  "myvar2": "hello",
  "myvar3": true
}
```

This will create variables with name `myvar1`, `myvar2` and `myvar3`.

If you use complex objects (array and object) then the variable name will be based on each property name from the root to a simple value property:
```json
{
  "myarray": [
    {
      "myobject": {
        "myvar": "hello"
      }
    },
    {
      "myobject": {
        "myvar2": "world"
      }
    }
  ]
}
```

This will create variables with the name `myarray.0.myobject.myvar` and `myarray.1.myobject.myvar2`. You can change the separator `.` with the parameter `Variable separator`

For YAML files those are converted to JSON and the same naming rule is applied.

**Comment by DaleyKD** [comment]
Is there a way we can add this to the README.md? It took me a little bit of searching to find this answer.

Thanks *SO* much for this task. This and the XDT transform saves my hide all the time.
