### ISSUE TITLE
Ability to output the variable group source in logs?

### ISSUE THREAD

**Issue by gismondigm** [qetza/vsts-replacetokens-task#243]
Hi, is there any type of logging that will show which token replace came from what library variable group and/or yaml file?
For example, if my pipeline is using multiple variable groups 

`ServerA: server1234 - Source: LibraryVariableGroupA`
 `ServerB: server5678 - Source: LibraryVariableGroupB`
`ServerC: server91011 - Source: LibraryYamlGroupC.yml`

**Comment by qetza** [comment]
Hi @gismondigm,
This information is not available when executing a task as the engine has already merged all variables and just expose the result.
