### ISSUE TITLE
Cannot see "Replace Tokens" in Azure DevOps pipeline task list, cannot configure.

### ISSUE THREAD

**Issue by AllanTee** [qetza/vsts-replacetokens-task#244]
It says: "Installed", but I cannot see "Replace Tokens" in Azure DevOps pipeline task list, cannot configure.

**Comment by AllanTee** [comment]
Hi, I finally found a way to include extension to the Task List. It was tricky and most confusing thing I can imagine. Thank you.

**Comment by qetza** [comment]
Hi @AllanTee,
Glad it's working for you.
