### ISSUE TITLE
System.debug does not set verbosity to detailed

### ISSUE THREAD

**Issue by PehrGit** [qetza/vsts-replacetokens-task#249]
Tested with version 3.9.1 and 4.1.1

I'm running a pipeline with the system.debug variable set to true, as you can see here:
![image](https://user-images.githubusercontent.com/3782086/150808140-204f667e-f54b-45cf-964f-408a2224dc03.png)

But I'm not getting the detailed verbosity:
![image](https://user-images.githubusercontent.com/3782086/150808446-500bfc23-ec7e-4b7e-9986-b358c7b640c7.png)

When I explicitly set `verbosity: detailed` it does give more detailed logging. (Tokens not expanded for privacy):
![image](https://user-images.githubusercontent.com/3782086/150808602-b1e1bf9f-876f-47a2-9fa5-bed11049fdcf.png)

**Comment by qetza** [comment]
Hi @PehrGit,
Thanks for the feedback, i never thought of linking the internal log verbosity and the default agent verbosity. I'll add this to a next version: if `system.debug` is set to `true` then verbosity in the task will be forced to `detailed`

**Comment by qetza** [comment]
Hi @PehrGit,
I've answered a little quick, this behavior is already implemented in the task: every log is always pushed to the system debug log.

### Test without system.debug and normal verbosity:
![image](https://user-images.githubusercontent.com/8191369/151695537-35ee7839-3b2a-490e-aea4-9da77b55c84b.png)
(system.debug = false)

![image](https://user-images.githubusercontent.com/8191369/151695547-8c922a92-272f-4028-ae08-4dfcdc77556c.png)
(replace tokens only showing normal logs)

### Test with system.debug and normal verbosity:
![image](https://user-images.githubusercontent.com/8191369/151695590-2a7fc2d5-0572-427a-8272-29abf1491bd0.png)
(system.debug = true and debug logs in purple)

![image](https://user-images.githubusercontent.com/8191369/151695620-9de57318-3502-40f3-95ee-9a0079c5e802.png)
(replace tokens showing normal logs and detailed logs as debug logs in purple)

**Comment by PehrGit** [comment]
Hi @qetza I see it working now in another one of our pipelines so I must have made a mistake in my test somewhere. My bad! If I do encounter the problem again i will re-open but for now it seems I was mistaken :)
