### ISSUE TITLE
Empty variable not respected in replace tokens task

### ISSUE THREAD

**Issue by tobidemski** [qetza/vsts-replacetokens-task#253]
Hey guys,

we are facing an issue with the Replacing Tokens Task.
We defined a variable in devops release pipeline
Variable: myHostname
Value: 

We set for a specific environment through the "Scope" a hostname but the default (Scope: Release) should be empty.

Logs shown by the initialize job: 
"[MYHOSTNAME] --> []"

In the Replace tokens task we are getting following message:
"2022-02-10T17:05:09.5410915Z ##[warning]  variable not found: myHostname"

All other variables are respected by the task and gets replaced by the defined values.
This is the only empty variable we have so far.

Replace Tokens Version: 3.9.1

Is this a known issue in 3.9.1 and we need to update to 5 or anyone knows a solution for this behavior?

Best regards
Tobi

**Comment by qetza** [comment]
Hi @tobidemski,
For empty value variables there is a catch as in the task there is no way to distinguish between an empty value and a missing variable (the SDK return an empty value for both).

If you want to have an explicit empty value then you have to set your variable to `(empty)` (this magic string is defined in the parameter _Empty value_).

**Comment by tobidemski** [comment]
Hey @qetza 

thanks for the fast response! I wasnt aware of this "Feature"/ Workaround but it seems it worked. Glad there is a solution :D
I will close this ticket. Thank you!
