### ISSUE TITLE
Replace Token - Installed - Not visible in Build and release under utility / All

### ISSUE THREAD

**Issue by govindarajan69** [qetza/vsts-replacetokens-task#26]
Hi Guys,

I installed Replace Token extension to TFS 2015.  I restarted the server also but could not find this in Build or Release.

Kindly suggest a solution.

Regards
Govinda

**Comment by qetza** [comment]
Hi @govindarajan69,
What update of TFS 2015 are you using? Can you see the extension on the installed extension tab?

Guillaume

**Comment by govindarajan69** [comment]
Hi Guillaume,

It is with Update 2 in production.  Update 3 in test environment.  I can see the extension on the extension tab.  When I click the install button again, it is saying "already installed".  I can see the other extensions are appearing when I installed.  Facing issues with only Replace Token.

regards
Govinda

**Comment by qetza** [comment]
I'll try to do some testing on my side and see if i can reproduce the issue and fix it.

Did you try also to force refresh the build / release page? (during dev sometimes i had browser cache which didn't show my updates)

**Comment by govindarajan69** [comment]
Hi,

infact I tried all combinations.  restarted the browser. cleared the cache and restarted the server also.

No luck.  that's why I posted this.

Thanks in advance for your immediate support.

Regards
Govinda

**Comment by govindarajan69** [comment]
Hi,
Thanks.  It worked.  I can see the icon now.  

![screenshot](https://cloud.githubusercontent.com/assets/25192340/22105198/f00d249a-de68-11e6-91ff-caf0ee347370.png)

Regards
Govinda

**Comment by qetza** [comment]
Glad it works. I'm closing the issue.
