### ISSUE TITLE
Root Directory Not found

### ISSUE THREAD

**Issue by mayurkharche07** [qetza/vsts-replacetokens-task#267]
Hi,
Earlier we were using 3.9.1 version for Replace Token but now the code is picking the updated on it own.
Current Version it is showing 4.2.0, but while running the pipeline we are getting below error while replcing the tokens.
Error : ##[error]Not found rootDirectory: /agent/_work/1/s/kits/jumpstart-oracle

just for your information, we are using below code in yaml file 
                - task: qetza.replacetokens.replacetokens-task.replacetokens@4
                   
Request you to kindly check and provide the RC. We'll change accordingly in our code.

Appreciate your help in advance !!!

Thanks, MK

**Comment by qetza** [comment]
Hi @mayurkharche07 ,
It is strange that you when from 3.9.1 to 4.2.0 as the auto update should keep the major version and you should have 3.10.0.
Can you share some debug log ne make sure that the directory exists?

**Comment by mayurkharche07** [comment]
Hi,

It picked 3.10.0 when there was @3 in task but when I changed it to @4 it is picking 4.2.0

Can you please suggest which version should I use and do we have to change anything in the root dir path ?

**Comment by qetza** [comment]
I would recommend staying on version 3 as they are breaking changes in version 4 that would have you update you task parameters or files.
But between version 3.9.1 and 3.10.0 there was no change in the code around the root directory.

**Comment by pratikkhurana** [comment]
Hi qetza,
We are using the Replace Token Version in Layers.yaml file with ‘@3’ so it is fetching the latest version which starts from 3.* i.e.3.10.1 and failing. If we use the specific version in yaml file like 3.9.1 then we get an error like this :

Encountered error(s) while parsing pipeline YAML:
Invalid step task reference qetza.replacetokens.replacetokens-task.replacetokens@3.9.1.

Pls suggest.

**Comment by qetza** [comment]
Hi @pratikkhurana,
You cannot specify a minor or patch version only the major version, the agent automatically gets the latest version for the specified major version.

The error you have comes from the SDK when the task is reading the the input parameter rootDirectory and doing a check if the directory exists. Are you sur that the directory really exists?

**Comment by mayurkharche07** [comment]
Hi qetza,
Can you suggest how can we check the directory ?
What is the actual functionality of this job ?

Because we commented this code from pipeline and pipeline executed successfully. Just wanted to check that we are using that functionality or not in our code.

Appreciate your help in advance !!

Thanks

**Comment by pratikkhurana** [comment]
we are using this path in code: 
rootDirectory: "$(System.DefaultWorkingDirectory)/kits/jumpstart-oracle"

Could you pls check if the path is correct? where is the  System.DefaultWorkingDirectory pointing to?

**Comment by pratikkhurana** [comment]
> Hi @pratikkhurana, You cannot specify a minor or patch version only the major version, the agent automatically gets the latest version for the specified major version.
> 
> The error you have comes from the SDK when the task is reading the the input parameter rootDirectory and doing a check if the directory exists. Are you sur that the directory really exists?

Not sure really. we dont know where that System.DefaultWorkingDirectory is pointing to.

**Comment by qetza** [comment]
Hi @mayurkharche07,
The task is reading the text files you specify in the target files parameter to find tokens and if found replace them with the variable value having the same name as the token.
For example if it finds the token `#{myvar}#` it will try to replace it with the value from the variable `myvar`.

To check if the directory exist, you could try to connect to your build agent if you can or if not you can always add to your pipeline a powershell/bash task to dump the list of folders in the current working directory of the agent.

**Comment by qetza** [comment]
Hi @1000986-PHS,
I just checked the code between version 4.1.1 and 4.2.0 and there was no change on the call to get the root directory parameter, it was already calling the SDK method `getPathInput` with a parameter to check the existence of the path and i didn't change the SDK version.
I don't see another explanation that your path doesn't exists anymore.

**Comment by qetza** [comment]
Hi @pratikkhurana,
`$(System.DefaultWorkingDirectory)` is a variable managed by the build agent and points to the current working directory of the agent for the build execution.
Based on the logs in the first message it seems to have the value `/agent/_work/1/s` which is correct. This is the path where the source code is downloaded, maybe you can check that the path `/kits/jumpstart-oracle` still exists in your source code and that the source code is correctly downloaded.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
