### ISSUE TITLE
Negative path on a folder and its subfolders

### ISSUE THREAD

**Issue by RadwaneMabchour** [qetza/vsts-replacetokens-task#269]
Hello !

I was trying to prevent the replacement to be done on a specific folder and all its subfolders, I've tried this `targetFiles: '**;!docker/lib/*'`, it works for the files directly under the `docker/lib/` folder but it still check its subfolders.
Is there way to do so ?
Thanks in advance !
--
Radwane

**Comment by qetza** [comment]
Hi @RadwaneMabchour,
The pattern `!docker/lib/*` is not a recursive pattern that's why it only excludes the files in the directory `docker/lib`. If you want to also exclude subdirectories then you need to use the pattern `!docker/lib/**/*` to make this recursive.
