### ISSUE TITLE
Does not seem to work on linux

### ISSUE THREAD

**Issue by kimptoc** [qetza/vsts-replacetokens-task#27]
I get error about only node handler available.

Is a way to get PowerShell on Linux yet?  Presuming not...

I guess we'd need to write a node version to support this.

Cheers,
Chris

**Comment by qetza** [comment]
Hi @kimptoc,
Which version of the task are you using? The latest version (2.0) was written in typescript and should work on Linux.

Guillaume

**Comment by kimptoc** [comment]
Doh - I see we have 1.4.1.  Will give v2 a go!

Thank you!

**Comment by kimptoc** [comment]
Oh - I see v2 needs TFS 2017 - we are still on 2015 - but going there next weekend :)

Cheers.

**Comment by qetza** [comment]
Remember that you will need to use the new cross platform agent (2.x).

**Comment by qetza** [comment]
Hi @kimptoc, i'm closing the issue but feel free to reopen it if you have an issue after your migration.

**Comment by kimptoc** [comment]
Sure.  We've moved to TFS 2017 but there seems to be some general issues around plugin versions.  Thanks again
