### ISSUE TITLE
Linux agent support?

### ISSUE THREAD

**Issue by x-meowzilla** [qetza/vsts-replacetokens-task#270]
Hello,

Not sure if this question has been asked before.
Is this task support Linux agent? I have tried token replacement in a Linux agent, but it was not able to find the tokens.
Btw, Windows agent works as expected.
I am currently using @2 version (I know it is old, we need to upgrade this task)

Thanks

```
==============================================================================
Task         : Replace Tokens
Description  : Replace tokens in files
Version      : 2.1.0
Author       : Guillaume Rouchon
Help         : [More Information](https://github.com/qetza/vsts-replacetokens-task#readme)
==============================================================================
replacing tokens in: /home/vsts/work/1/s/PROJECT_NAME/AppSettings/appsettings.json
(node:1812) Warning: Use Cipheriv for counter mode of aes-256-ctr
...
##[warning]variable not found: secret1
##[warning]variable not found: secret2
##[warning]variable not found: secret3
```

**Comment by qetza** [comment]
Hi @x-meowzilla,
Version 2.x is not compatible with Linux agents you will have to upgrade to version 3.x and preferably version 5.x as node6 is being deprecated (used by 3.x and 4.x)

**Comment by x-meowzilla** [comment]
thank you very much!
