### ISSUE TITLE
[question] how to build with make.js

### ISSUE THREAD

**Issue by paulovila** [qetza/vsts-replacetokens-task#274]
Hi, I wanted to fork this extension to run on it a private organisation. I'm using ```npx tfx-cli extension create``` to create the package, but doesn't seem to work after installing it, saying:

```##[error]File not found: 'D:\a\_tasks\replacetokens_a8515ec8-7254-4ffd-912c-86772e2b5962\5.1.0\index.js```

   I'm wondering if I'm missing out something with make.js. how do you run make.js?

**Comment by qetza** [comment]
Hi @paulovila,

If you want you have the packaged extensions (.vsix) available in the [releases ](https://github.com/qetza/vsts-replacetokens-task/releases) on GitHub.

If you want to build and package your own vsix here is the command line:

```
node make build package --taskId 'your unique task id' --iKey 'your unique app insight instrumentation key' --extensionId 'your unique extension id'
```
