### ISSUE TITLE
Unable to Replace the Key

### ISSUE THREAD

**Issue by shujaatxp** [qetza/vsts-replacetokens-task#275]
When i checked artifact zip file, nothing is changing.

**Comment by shujaatxp** [comment]
its said   : replaced 2 tokens out of 2 in 13 file(s) in 0.099 seconds.  but when i check actual file, nothing is changed.

"ConnectionStrings": {
    "AppDatabase": "#{ConnectionStrings--AppDatabase}#"
  }

**Comment by qetza** [comment]
Hi @shujaatxp,
Maybe you are not changing the file which gets upload in the artifacts?

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
