### ISSUE TITLE
minimumAgentVersion need to be updated to 2.117.0

### ISSUE THREAD

**Issue by TheRealGI** [qetza/vsts-replacetokens-task#277]
Release: V4.4.0
Impacts: Task 4.2.0 & 3.10.0

With the latest release the issue #201 (PR: #257 ) was closed.
In this change the default parameter was used which requires node 6 or above. 
For the agent, node 6 or above was introduced with 2.117.0 (before node 5.10.1) [Source](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/docs/minagent.md#task-execution-handler).

The current minimumAgentVersion is set to 2.105.0 and needs to be updated to 2.117.0. Also updating the readme to point out  the change of requirements would be helpfull.

**Comment by qetza** [comment]
Hi @TheRealGI,
Thanks for pointing this issue, to avoid any breaking change by changing the minimum agent version i will remove the usage of the default parameter to be compatible with node 5.

**Comment by qetza** [comment]
A new version is published with the removal of default parameter.
