### ISSUE TITLE
Some password values in strings from Azure resources replaced with new line token replacement job

### ISSUE THREAD

**Issue by ozgurozkan123** [qetza/vsts-replacetokens-task#280]
Some password values produced by Azure resources that include some special characters translated as new line after replacement. It produces errors in yamls and various config files. Example password:

Zbx6Ayl5jwf6GWrVYM12DT+ESZubkBWv0oFVsLYC9zYzZ4Wy03cMlHMzbGo/50d0J2IdjrObRDbe8+ITYqUM7A== (/50 may be the root cause of the issue) 

Any password that include %0D also produce the same issue.

**Comment by qetza** [comment]
Hi @ozgurozkan123,
Thanks for reporting the issue, i'll look at it and if possible fix it :smile:

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
