### ISSUE TITLE
Errors in TFS 2017

### ISSUE THREAD

**Issue by WangoAndCash** [qetza/vsts-replacetokens-task#281]
Hi - we are using TFS 2017 on prem with agent 2.144.0 and Replace Tokens version 5.1. When I try to execute the task, I get the following errors: 

Unable to process command '##vso[task.setvariable variable=tokenReplacedCount;isOutput=false;issecret=false;]11' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
Value cannot be null. (Parameter 'RefName')
Unable to process command '##vso[task.setvariable variable=tokenFoundCount;isOutput=false;issecret=false;]11' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
Value cannot be null. (Parameter 'RefName')
Unable to process command '##vso[task.setvariable variable=fileProcessedCount;isOutput=false;issecret=false;]1' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
Value cannot be null. (Parameter 'RefName')
Unable to process command '##vso[task.setvariable variable=transformExecutedCount;isOutput=false;issecret=false;]0' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
Value cannot be null. (Parameter 'RefName')
Unable to process command '##vso[task.setvariable variable=defaultValueCount;isOutput=false;issecret=false;]0' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
Value cannot be null. (Parameter 'RefName')

**Comment by WangoAndCash** [comment]
Is there a chance that TFS 2017 doesn't support the isOutput parameter when setting a variable?

**Comment by qetza** [comment]
Hi @WangoAndCash,
Looking at the documentation on the logging commands it says Azure DevOps Server 2019 and TFS 2018 so maybe it is not supported. I'll ask the question on the azure pipelines sdk github.
Version 3 of the task is not writing output variables (as it was not supported by the minimum agent version it was developed for).

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
