### ISSUE TITLE
expected a single document in the stream, but found more

### ISSUE THREAD

**Issue by hullscotty1986** [qetza/vsts-replacetokens-task#287]
If you have a yaml file with multiple documents (split by ---) you get the error:
"expected a single document in the stream, but found more"
Can it process each document?

**Comment by qetza** [comment]
Hi @hullscotty1986,
Sorry for the late reply.

When you ask for support of YAML file with multiple document you mean in the variable file parameters?

I'll add support for YAML file with multiple documents in the next release as this is not a big development.

**Comment by hullscotty1986** [comment]
Hi @qetza 

No worries, I know we are all busy!

I mean I tried passing it multiple yamls in one file e.g:

document: this is document 1
---
document: this is document 2

And it throws the above "expected a single document in the stream, but found more"

**Comment by qetza** [comment]
Hi @hullscotty1986,
A new version of the task is released and contains support for multiple documents in YAML files both in variable files and inline variables.
