### ISSUE TITLE
Secret variables can not be found

### ISSUE THREAD

**Issue by dnperfors** [qetza/vsts-replacetokens-task#29]
When trying to use the replace tokens task in our release, I found that variables that are marked as secret are can not be found.

I have a variable called 'ConnectionString' in our configuration set as secret, because it contains a password. The ReplaceTokens task generated the following warning:
##[warning]variable not found: ConnectionString

Can support for secret variables be added, or could you at least mention that they are not supported?

Regards,
David Perfors

**Comment by qetza** [comment]
Hi @dnperfors,
The task handles secret variables without any special configuration. Could you enable debug logs and share them?
To enable debug log, just add the variable `system.debug` with the value `true`.

**Comment by dnperfors** [comment]
Hi @qetza,

I tried to get the debug log and found out it is working now. Last night they update our TFS Server to Update 1 which might have solved this issue.
