### ISSUE TITLE
Getting error 'The system cannot find the file specified.' in Release Pipeline

### ISSUE THREAD

**Issue by cchamberlain2022** [qetza/vsts-replacetokens-task#293]
I keep getting a 'The system cannot find the file specified.' error when my Replace Tokens task is running.  It is added to an agent job in a release pipeline and it has the default settings.  Any ideas why I'm getting this error?

**Comment by qetza** [comment]
Hi @cchamberlain2022,
Could you share the debug logs as i have no idea like this of what could be the issue.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
