### ISSUE TITLE
Can't replace nested objects in appsettings file?

### ISSUE THREAD

**Issue by JGSilverman** [qetza/vsts-replacetokens-task#294]
Using ReplaceTokens@3:

I have an appsettings.json file which has an object like so:

```
{
   "Data": {
      "myProperty": "#{myProperty}#"
    }
}
```

In my devops variable group library that is injected into my AzureDevops build, I have a key of Data.myProperty

Then I use the replace tokens task with prefix of '#{' and suffix of '}#' and target my file.

The log says 1 of 1 replaced, but when i look at the outputted artifact, it has not been replaced.

If I put myProperty OUTSIDE of the appsettings.Data object, then it works.

What is the correct syntax to target nested object properties?

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
