### ISSUE TITLE
Visual Studio Code support

### ISSUE THREAD

**Issue by DillyBabu** [qetza/vsts-replacetokens-task#295]
I have no issues to complain here, This is a nice tool available while using Azure Devops. But, I would like to know, is there any plan to bring this support to visual studio code also?

**Comment by DillyBabu** [comment]
Hi @qetza, This is a sample issue: I am developing terraform modules and my git repo will be accessed only using PAT token. In Azure Devops I am using Replace Tokens task where it works fine. But, during development using visual studio code I have no other option than to use search and Replace.
I wanted to change #{gitUser}# and #{gitAccessToken}# with real(hidden) values
```
source              = "git::https://#{gitUser}#:#{gitAccessToken}#@github.com/myrepo/RG-Module"
```

**Comment by qetza** [comment]
Hi @DillyBabu,
I think i have a simple powershell script somewhere which mimics the simple replace tokens (no transformations and advance features) by taking your file, a json file with the variable values and outputing the result to the console. Could this help you?

**Comment by DillyBabu** [comment]
Hello @qetza , Thanks for your reply. Could you please share me the script? I will try and let you know.

**Comment by qetza** [comment]
@DillyBabu,
You now have a CLI available to run locally `npm i -g @qetza/replacetokens`

I'm archiving the project and moving it to a new repository https://github.com/qetza/replacetokens-task
