### ISSUE TITLE
Replace Token adds \ in path

### ISSUE THREAD

**Issue by AkashSatoliya** [qetza/vsts-replacetokens-task#296]
I'm using the replace token to replace variable in appsettings.json file. 
The variable in classic release pipeline is defined as below:
```
LogPath =  C:\Path\To\The\Log\File\{Date}.log
```
Token in apsettings.json file is as below:
```
LogPath = "@@LogPath@@",
```

After token replacement in appsettings.json, the value should be like
```
LogPath = "C:\Path\To\The\Log\File\{Date}.log",
```
But it is as below:
```
LogPath = "C:\\Path\\To\\The\\Log\\File\\{Date}.log",
```

It adds additional `\` in the path.

Please assist.

Thanks

**Comment by qetza** [comment]
Hi @AkashSatoliya,
This is normal as backslashes are special characters in JSON and needs to be escaped. As the file is a JSON file the task automatically escape special characters in variable values so that your resulting file is a valid JSON file.

**Comment by AkashSatoliya** [comment]
Thanks @qetza.
