### ISSUE TITLE
Comments in JSON File Cause Exception

### ISSUE THREAD

**Issue by DaleyKD** [qetza/vsts-replacetokens-task#299]
I realize that official JSON files don't support comments. However, .jsonc files aren't as fussy. 😄 

I'm trying to use a .jsonc file (because I want to help our developers know what each token replace means/does). In PowerShell, `ConvertFrom-Json` does not seem to get upset if there are comments.

Is it possible for this task to allow comments? I know I COULD use YAML, but that causes another issue further down the path.

Thank you for your consideration.

**Comment by qetza** [comment]
Hi @DaleyKD,
I'll try to find a library which can read JSON with comments or strip comments before parsing the files and use it instead of the standard library.

**Comment by DaleyKD** [comment]
@qetza : That would be glorious. Thank you!

**Comment by DaleyKD** [comment]
I have no idea, but I stumbled across JSON5.org today.

**Comment by qetza** [comment]
Hi @DaleyKD,
A new version of the task is released and contains support for comments in JSON variable files.
