### ISSUE TITLE
Permission issues on *nix systems

### ISSUE THREAD

**Issue by artberri** [qetza/vsts-replacetokens-task#30]
Hi,

If you use this task on a Linux system, the files become unusable after the replacement because of this line:
https://github.com/qetza/vsts-replacetokens-task/blob/master/task/index.ts#L148

Is that line something needed for Windows system? Why a permission change is needed?

I think that the files should keep the permissions they had before the replacement is done, but if this is something required on windows to work I can try to find a possible fix and make a PR, because for Linux you should set the permissions like this:

```js
fs.chmodSync(filePath, '0666');
```

But IMHO that line is not needed. Do you want me to make a PR removing that line?

**Comment by qetza** [comment]
Hi,

Thanks for your comment; the change of permission is for people using TFVC as source control where files are by default readonly.

I think the best solution will be to have your fix with the correct permission value if it also works on windows. I'll do the fix tonight and test on windows and linux. Can you tell me what action i can do on linux after changing the file to see if it works?

**Comment by artberri** [comment]
You just need to do a `ls -l /path/to/the/file` and check the permissions.

I'll recommend you to don't execute any permission change in Linux (it is not really needed and you may be removing execution permissions when there are needed), but of course, it needs you to find the way to differentiate the OS. 

If at the end you need to give `666` in both OS, this is how wrong looks like:
![screenshot from 2017-03-23 16-03-59](https://cloud.githubusercontent.com/assets/454523/24254136/630b1b00-0fe2-11e7-9022-1a878a57f607.png)

And this is how `666` permissions should look like:
![screenshot from 2017-03-23 16-04-07](https://cloud.githubusercontent.com/assets/454523/24254137/630ca38a-0fe2-11e7-8391-3e0aac9f8a87.png)

Thank you!

**Comment by qetza** [comment]
This is now fixed in version 2.0.2 which i just deployed.

After testing, I've removed the command to change the permissions as it was not needed anymore.

Thanks for submiting the issue.

**Comment by artberri** [comment]
Thanks to you for fixing it :+1:
