### ISSUE TITLE
Add this task to Github actions marketplace?

### ISSUE THREAD

**Issue by crayon-robertelliott** [qetza/vsts-replacetokens-task#300]
Are there any plans to be able to convert this task for GitHub actions? There are many replace token actions in the GitHub marketplace but none as robust as this one for Azure DevOps, from what I can see. I think the closest action is this one - https://github.com/marketplace/actions/replace-tokens - which actually was inspired by this task.

**Comment by crayon-robertelliott** [comment]
The reason I ask is I'm trying to find an action that can take a json file with values and replace those values into other files. This task can do it in Azure DevOps but it doesn't look like GitHub actions has something that can do this. Unless I take the json file values out and create a bunch of env variables inside the workflow yaml file using the above-mentioned action. If anyone has suggestions.

**Comment by qetza** [comment]
Hi @crayon-robertelliott,
Sorry for the delay, the task is now available as a GitHub Action https://github.com/marketplace/actions/replacetokens

I'm archiving the project and moving it to a new repository https://github.com/qetza/replacetokens-task
