### ISSUE TITLE
[Feature Request] Convert string to JSON

### ISSUE THREAD

**Issue by celluj34** [qetza/vsts-replacetokens-task#302]
Hello;

There is some context which I will not bore you with, but the short version is, I have a string (which is JSON) in a runtime variable but I want to write the _actual_ JSON to a file (_not_ the string representation).

Is there a way (or can a way be introduced) to convert a string to JSON when writing to a file? I envision it would be another transform, `convertToJson` or `json` or `toJson` or something like that.

Let me know if you need any more info. Thanks!

**Comment by qetza** [comment]
Hi @celluj34,
By default the task will escape all variable values if your file is a JSON so effectively you will not be able to inject raw JSON but there is a transform `noescape` that will diable this behavior for the specified variable.


So if you have a variable `string_value` with the value `some "auto escaped" value` and a variable `obj_value` with the value:
```json
{
  "message": "hello world!"
}
```

and in your file where you replace you put:
```json
{
  "value": "#{string_value}#",
  "obj": #{noescape(obj_value)}#
}
```

then the output will be:
```json
{
  "value": "some \"auto escaped\" value",
  "obj": {
    "message": "hello world!"
  }
}
```

**Comment by celluj34** [comment]
I don't remember what the context was around this request, but I think I eventually got this sorted out on my own. I think my issue was I had JSON in a YML string, and when it was being written to the file it was still getting wrapped in quotes. I am now using the noescape helper but I think with some azure devops + yml shenanigans.

Thanks for replying; I think I am all set for now!
