### ISSUE TITLE
 wrong information files web.config and app.config as xml to .net projects

### ISSUE THREAD

**Issue by JulioCesarEvangelista** [qetza/vsts-replacetokens-task#303]
Hi,

I use your library to replace token in our projects .net.
When I use .net 6 and the configuration is in appsettings.json work well, but when I use .net framework 4.8 and the file configuration is web.config as xml the replacement token happen and print like not happend.

eg: replaced 0 tokens out of 0 in 7 file(s) in 0.095 seconds

**Comment by qetza** [comment]
Hi @JulioCesarEvangelista,
You can activate debug logging and see more information. Based on the log there was no token found so i think that your tokens in the web.config files don't have the correct token prefixes and suffixes.

**Comment by qetza** [comment]
I'm archiving the project and moving it to a new repository https://github.com/qetza/replacetokens-task
