### ISSUE TITLE
Vulnerability Issue Found

### ISSUE THREAD

**Issue by Soni-VL** [qetza/vsts-replacetokens-task#304]
Vulnerability issue found in the code, kindly suggest who is the responsible person to contact and report the issue.

@qetza, could you please suggest who is the responsible person to contact and report the vulnerability issue?

**Comment by qetza** [comment]
Hi @Soni-VL,
You can contact me on my gmail account qetzac.

**Comment by karpikpl** [comment]
Was the vulnerability addressed?

**Comment by qetza** [comment]
I'm archiving the project and moving it to a new repository https://github.com/qetza/replacetokens-task
