### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by maitriyogin** [qetza/vsts-replacetokens-task#306]
Hi,
we've just setup an M1 agent for our pipeline.
The consequence is super fast builds but also this error when applying replace tokens:
Bad CPU type in executable

I guess I need to install rosetta on the M1 ?

or, is it possible to provide an arm build?

/Stephen.

**Comment by qetza** [comment]
Hi @maitriyogin, the task is in javascript so there is no build it is just run by node on the build server.
I didn't update the task to support the Node16 runner so maybe that's the issue. This support will be added to the next release.

**Comment by qetza** [comment]
Hi @maitriyogin,
I've released a new version with support for Node16 in version 5 of the task. Does this correct your issue?

**Comment by qetza** [comment]
I'm archiving the project and moving it to a new repository https://github.com/qetza/replacetokens-task
