### ISSUE TITLE
Replace token can incorrectly detect recursion cycle

### ISSUE THREAD

**Issue by chad-smith** [qetza/vsts-replacetokens-task#308]
Our team recently started receiving an error when transforming config such as:

```
##[error]recursion cycle with token 'EnableConsole'.
```

Renaming the token caused the issue to go away. Narrowing it down within the code, it seems that in rare cicumstances this causes an issue because the code is accidentally looking for the token name within a string representation of all existing tokens.

This means (as was the case in our setup) that it would find an existing usage of `EnableConsole` within a usage of a variable called `AlwaysEnableConsoleWarnings`.

I'm not sure how you'd like to accept contributions or where we might stand with versioning, but I am raising a pull request now as a means to demonstrate where in the code the issue occurs.

**Comment by Malgefor** [comment]
When can we expect the PR to be merged and a new version of the task to be released @qetza ? Running into the same issue as @chad-smith

**Comment by qetza** [comment]
Hi @chad-smith, @Malgefor,
A new version of the task is released and contains the fix for variable recursion detection. Thanks again @chad-smith for the PR.
