### ISSUE TITLE
ReplaceTokens does replace - KubernetesManifest task says it doesn't recognize variable

### ISSUE THREAD

**Issue by vinceweeks-69** [qetza/vsts-replacetokens-task#310]
here are my files

configmap.yaml
apiVersion: v1
kind: ConfigMap

metadata:
  name: dsdvendorservice-settings
  labels:
    app: dsdvendorservice

data:
   # This is populated by the shared deploy pipeline template's ReplaceTokens task
  BusinessEnvironment: #{EnvironmentName}#
  # These are populated by the shared pipeline key-vault-db-connections templates's ReplaceTokens task'
  DbConnection: #{DbConnectionTCIS}#  

Here's my template:
parameters:
#- group: variableGroup
- name: EnvironmentName
  default: ""
- name: AzureSubscription
  default: ""
- name: KeyVaultName
  default: ""
- name: DbConnectionTCIS
  default: ""
#- name: DbConnection2
#  default: ""
#- name: DbConnection3
#  default: ""
- name: Manifests
  default: ""

stages:
- stage: GetFromKeyVault_${{ parameters.EnvironmentName }}
  jobs:
  - job: KeyVault_${{ parameters.EnvironmentName }}
    displayName: KeyVault_${{ parameters.EnvironmentName }}

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    #- group: ${{parameters.variableGroup}}
    - name: EnvironmentName
      value: ${{parameters.EnvironmentName}}
    - name: DbConnectionTCIS
      value: ${{parameters.DbConnectionTCIS}}
    #- name: DbConnection2
    #  value: ${{parameters.DbConnection2}}
    #- name: DbConnection3
    #  value: ${{parameters.DbConnection3}}

    steps:
      - checkout: self
      
      # Azure Key Vault v2
      # Download Azure Key Vault secrets.
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: ${{parameters.AzureSubscription}} # string. Alias: ConnectedServiceName. Required. Azure subscription. 
          KeyVaultName: ${{parameters.KeyVaultName}} # string. Required. Key vault. 
          SecretsFilter: '*' # string. Required. Secrets filter. Default: *.
          #RunAsPreJob: false # boolean. Make secrets available to whole job. Default: false.

      - powershell: Write-Output "DbConnection = $DbConnectionTCIS"
          
      - task: replacetokens@3 # Replaces the tokens found in the yml files according to variables provided
        inputs:
          targetFiles: ${{ parameters.Manifests }}
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          useLegacyPattern: false
          enableTelemetry: true

Here's the pipeline yaml that calls the template (partial)
trigger:
  branches:
    include:
    - "releases/*"
    
# This defines where to find shared yml files to be used as templates
resources:
 repositories:
   - repository: Shared
     name: SE Grocers/Pricing_Shared
     type: git
     ref: main

variables:
- name: dockerFilePath
  value: 'Dockerfile'
- name: rancherNamespace
  value: 'dsdvendorservice'
- name: DevApprovalEnv
  value: Pricing-Devs
- name: QAApprovalEnv
  value: Pricing-BAs
- name: Manifests
  value: |
    $(Build.SourcesDirectory)/Manifests/deployment.yml
    $(Build.SourcesDirectory)/Manifests/ingress.yml
    $(Build.SourcesDirectory)/Manifests/configmap.yml
    $(Build.SourcesDirectory)/Manifests/service.clusterip.yml

stages:
#Build and store image
- template: YAML/Builds/build-image.yml@Shared
  parameters:
    imageRepository: 'app/dsdvendorservice'
    dockerfilePath: $(dockerFilePath)

# run if this is not a PR
- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:

  ## Dev KeyVault
  - template: YAML/key-vault-db-connections.yml@Shared
    parameters:
      EnvironmentName: 'dev'
      AzureSubscription: 'XXXXXXXXX'
      KeyVaultName: 'kv-dsdvendorservice-dev'
      DbConnectionTCIS: ''
      Manifests: $(Manifests)

from the pipeline logs:

replacing tokens in: /home/vsts/work/1/s/Manifests/configmap.yml
##[debug]  using encoding: utf-8
##[debug]EnvironmentName=dev
##[debug]  EnvironmentName: dev
##[debug]DbConnection=undefined
##[warning]  variable not found: DbConnection
##[debug]Processed: ##vso[task.issue type=warning;]  variable not found: DbConnection
##[debug]  DbConnection: 
  1 token(s) replaced out of 2

from the next pipeline step:

error: error validating "/home/vsts/work/_temp/ConfigMap_dsdvendorservice-settings_1686833420867": error validating data: unknown object type "nil" in ConfigMap.data.DbConnection; if you choose to ignore these errors, turn validation off with --validate=false
deployment.apps/dsdvendorservice configured
ingress.networking.k8s.io/lb-dsdvendorservice unchanged
service/dsdvendorservice-clusterip unchanged
##[debug]KUBECONFIG=/home/vsts/work/_temp/kubectlTask/1686833410189/config
##[debug]set KUBECONFIG=
##[debug]Processed: ##vso[task.setvariable variable=KUBECONFIG;issecret=false;]
##[debug]task result: Failed
##[error]error: error validating "/home/vsts/work/_temp/ConfigMap_dsdvendorservice-settings_1686833420867": error validating data: unknown object type "nil" in ConfigMap.data.DbConnection; if you choose to ignore these errors, turn validation off with --validate=false
##[debug]Processed: ##vso[task.issue type=error;]error: error validating "/home/vsts/work/_temp/ConfigMap_dsdvendorservice-settings_1686833420867": error validating data: unknown object type "nil" in ConfigMap.data.DbConnection; if you choose to ignore these errors, turn validation off with --validate=false
##[debug]Processed: ##vso[task.complete result=Failed;]error: error validating "/home/vsts/work/_temp/ConfigMap_dsdvendorservice-settings_1686833420867": error validating data: unknown object type "nil" in ConfigMap.data.DbConnection; if you choose to ignore these errors, turn validation off with --validate=false
Finishing: KubernetesManifest

My question is one of trying to understand what ReplaceTokens does. From what I've read, the specified files have the recognized variables written with the appropriate data. Why does the KubernetesManifest task need to know about a variable from a seperate step?

**Comment by qetza** [comment]
Hi @vinceweeks-69,
From what i understand from the task logs you have define 2 tokens in the file `configmap.yml`: `#{EnvironmentName}#` and `#{DbConnection}#`.
The task tries to find 2 variables declared with the names `EnvironmentName` and `DbConnection` but only find the variable `EnvironmentName` so it replaces the token `#{EnvironmentName}#` with the variable value and replaces the token `#{DbConnection}#` with an empty string.
I think the empty string is then causing your issue in a later step. So you need to define the variable `DbConnection` with a correct value or rename the token to a variable having the correct value.

**Comment by qetza** [comment]
I'm archiving the project and moving it to a new repository https://github.com/qetza/replacetokens-task
