### ISSUE TITLE
Permissions needed by extension

### ISSUE THREAD

**Issue by BeckRobinGithub** [qetza/vsts-replacetokens-task#311]
Hi, I would love to add your extension to our build pipeline but due to company rules I have to first evaluate which permission an extension needs before it can be installed (e.g. Code (read), Build, ....) and if it stores some of their Data outside of our environment.

The latter one is probably answered by configuring the environment variable REPLACETOKENS_DISABLE_TELEMETRY right?

Thank you in advance if you could clarify the permissions the extension needs for me, that would be great

**Comment by qetza** [comment]
Hi @BeckRobinGithub,
For the data send outside as you have mentioned you can disable that through the environment variable `REPLACETOKENS_DISABLE_TELEMETRY` with a value of `0`.
For the permissions needed, as the extension is a pipeline task extension it does not interact with Azure DevOps so it does not need any permissions. The task will be run by the build agent and will have access to files that you pulled from your repository.

**Comment by BeckRobinGithub** [comment]
Hi @qetza thank you very much for your very quick reply, much appreciated. That was the information I needed.
Thanks again and have a wonderful day
