### ISSUE TITLE
variable empty valu

### ISSUE THREAD

**Issue by damhold** [qetza/vsts-replacetokens-task#32]
Hello.
What do i have to do if the variable has to be replaced by an empty value?
I use VSTS and i don't see the tab meesing variable action on the task.

Regards,

Damien

**Comment by qetza** [comment]
Hi Damien,
If you want to replace variables with empty values you have to:

- Expand the `Missing variables` group
- Select `silently continue` for action
- Uncheck `Keep token`

The group should be visible under the standard parameters.

**Comment by qetza** [comment]
Hi Damien,
Will a custom configurable value to specify empty value would suite your needs? For example configuring that variable value to `(empty)` would mean to replace the token with an empty value without triggering a warning or an error.

**Comment by damhold** [comment]
Hi Guillaume.
Yes It should be very nice.
I would like to keep all parameters between my different environments as if it is empty. It is for a uniformisation purpose...

Thanks a lot for your following 😀

Kind regards,

Damien Holderbeke
Mobile






Damien Holderbeke
Mobile

**Comment by qetza** [comment]
Hi Damien,
I just published a new version which exposes a new parameter `Empty value` which allows to replace tokens with an empty string when the variable value matches this parameter. The default empty value is `(empty)` and can be changed in the advanced tab.

**Comment by damhold** [comment]
Hi Guillaume 
Thanks a lot for the work. I will test it today and give you feedback
Hava a nice day

Best regards,

Damien

Damien Holderbeke
Mobile






Damien Holderbeke
Mobile

**Comment by damhold** [comment]
Hi.

Your change is working fine.
Thanks for the job.
You can close the issue.

Damien

**Comment by Philippe85** [comment]
The two parameters yaml "emptyValue" and "defaultvalue" (and the documentation) are not understandable !
How to use them ! Give us examples !
Why didn't you propose a "allowEmptyValues" parameter more clear and needn't documentation !

So, I want to authorise empty string, but fail task if a variable is not set. How to do in yaml ?
