### ISSUE TITLE
Delete files processed

### ISSUE THREAD

**Issue by luiz-soares** [qetza/vsts-replacetokens-task#320]
We have been using this task to replace tokens in *.release.config and save to *.config so we end up with both files in our apps which is redundant and may cause confusion as people could thing *.release.config are the actual ones.

Would you be willing to accept a PR to introduce a parameter/input which would delete 'source' files?

We don't always know all possible source/target files so we cannot have that hardcoded, another option I can think is an output variable with the list of touched source files.

Or if you have any other suggestions to do that.

Thanks for this task.

**Comment by qetza** [comment]
Hi @luiz-soares,
You could use the delete task (https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/delete-files-v1?view=azure-pipelines) and configure it with the same pattern(s) you used to match the source files in the replace token task.

I'll also see if i can include in the next release an output variable with the list of files, i prefer that the task do not do anything to existing file except replacing tokens.

**Comment by luiz-soares** [comment]
Thanks @qetza , it sits in a yaml template where we don't have control of the patterns sent to Replace Task and I'd like to avoid having to parse such parameter to find out all target files requested by the consuming pipeline.

I'm looking forwards for this change, thanks.

**Comment by qetza** [comment]
I'm archiving the project and moving it to a new repository https://github.com/qetza/replacetokens-task
