### ISSUE TITLE
Value in token is changed when replaced.

### ISSUE THREAD

**Issue by raphaeldeletoille** [qetza/vsts-replacetokens-task#325]
I have the exact same issue than https://github.com/qetza/vsts-replacetokens-task/issues/176

To answer the last comment, using single quote do not solve this issue.

Wanted to say thank you for a great tool you created. Using it for 3 years in all my depoyment pipelines.

To the issue:

Yesterday I migrated all my variables to yaml from libraries in a structure like this:

# Shared Variables across all stages
variables:
  vg.title: "Some Title"
  vg.appServiceSkuName: "F1"
  vg.dataFactorypipelineStart: "2020-01-01T22:32:00Z"
  #40 more values like that
My date "2020-01-01T22:32:00Z" is transformed into: "01/01/2020 22:32:00"
The issue did not occur when the variables where in the Azure Devops Libraries or before in the Classic Pipelines Variables.
The file in question is a parameters.json file for ARM template for deploying resources.

My task config:

- task: a8515ec8-7254-4ffd-912c-86772e2b5962@3
  displayName: 'Replace Tokens in ARM parameters'
  inputs:
    rootDirectory: '$(Pipeline.Workspace)/drop'
    targetFiles: '**/*.parameters.json'
    encoding: 'auto'
    writeBOM: true
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    emptyValue: ''
    enableTelemetry: false
    actionOnMissing: 'continue'
    verbosity: detailed
Note I tried multiple configurations with encoding being utf-8 and writeBOM being true and false.

Also to double check what is happening and enclosed the value in additional single quotes like this: "'2020-01-01T22:32:00Z'"
And the date was not transformed but kept the single quotes that are not desirable.

**Comment by qetza** [comment]
Hi @raphaeldeletoille,
After doing some testing the issue seems to come from the azure pipeline agent directly as the variable values set as environment variables to be available to the task are already in the incorrect format.
I'll open an issue on the agent repository.

**Comment by qetza** [comment]
I'm archiving the project and moving it to a new repository https://github.com/qetza/replacetokens-task
