### ISSUE TITLE
Preserve Data Type

### ISSUE THREAD

**Issue by haydenhancock** [qetza/vsts-replacetokens-task#327]
Is there a way to preserve the data type without having to have non-valid JSON object? Say I want to the final `.json` file.

```json
{
    "Number": 1,
    "Fruits": [ "Apple", "Orange" ]
}
```
The tokenized version would look like but this isn't valid JSON.

```json
{
    "Number": #{Number}#,
    "Fruits": #{Fruits}#
}
```

Is this the expected way to preserve data types when using this task?

**Comment by qetza** [comment]
Hi @haydenhancock,
The task is doing a simple find and replace on your text file, so there's no way to have a valid json file with token replacing anything but strings.

**Comment by haydenhancock** [comment]
Thanks for the reply!
