### ISSUE TITLE
Looking for documentations on how the extension manages data

### ISSUE THREAD

**Issue by fRanK45jPm** [qetza/vsts-replacetokens-task#331]
Hello, I am looking for any documentations on how the extension is managing Azure DevOps data?

Thank you
John

**Comment by qetza** [comment]
Hi @fRanK45jPm,
The only documentation is in the readme file. The extension is only accessing the variables defines in your pipeline and for telemetry it is getting a hash of the azure devops account id, project id and build definition id.

**Comment by qetza** [comment]
I'm archiving the project and moving it to a new repository https://github.com/qetza/replacetokens-task
