### ISSUE TITLE
Token Replace multiple tokens

### ISSUE THREAD

**Issue by sinyce1959** [qetza/vsts-replacetokens-task#333]
I have three tokens in my app.config file but I only want to replace one token which is defined in ADO Library

#{octo-url}#
#{octo-kv}#
#{octo-kvsecret}#

I only want to replace the first token, and leave the other two as is, future programming.
The Deployment runs fine but warns that it finds the other two, but there is no variable defined for them.
Any idea?

**Comment by qetza** [comment]
Hi @sinyce1959,
If you want to just remove the warning messages when no variable is found you can set the input `actionOnMissing` to `continue`.

**Comment by sinyce1959** [comment]
Thanks that worked perfectly.
- task: qetza.replacetokens.replacetokens-task.replacetokens@5  <-- is there any reason why ADO is telling me that the task name should be that, and not just replacetokens@5 ?
- No biggie, it works fine. Just wondering.

**Comment by qetza** [comment]
That's because it's a custom task so you have to use the "fully qualified" name which contains the publisher name, the extension id and the task name

**Comment by qetza** [comment]
I'm archiving the project and moving it to a new repository https://github.com/qetza/replacetokens-task
