### ISSUE TITLE
Cannot use variable for Target Files

### ISSUE THREAD

**Issue by RyanElfman** [qetza/vsts-replacetokens-task#35]
I'd like to be able to dynamically set the Target Files parameter but I can't seem to specify multiple paths when using a VSTS variable such as $(Testing) due to the delimiter being a newline character. Is there any workarounds for this?

**Comment by qetza** [comment]
Hi Ryan,

I've never tried to use a multiline variable. Currently the split is done on the character `\n`, did you try to include this in your variable?

`file01.txt\nfile02.txt`

If this doesn't work i'll do an update to allow to split on comma `,` also.

**Comment by RyanElfman** [comment]
Hi qetza,

I've tried multiple things. \n \\n /n //n with no luck. Even tried using the Alt+013 character.

Ryan

**Comment by qetza** [comment]
Hi Ryan,
I'll then add in the next release (maybe this week end) support for comma delimiter.

Guillaume

**Comment by RyanElfman** [comment]
Any update on this?

**Comment by qetza** [comment]
Hi Ryan,
I've published a new version which now supports comma `,` as a separator.
