### ISSUE TITLE
Not replacing build numer

### ISSUE THREAD

**Issue by lcmassena** [qetza/vsts-replacetokens-task#39]
I am trying to replace __Version__ and __VersionDate__ with my Variable "$(Env:BUILD_BUILDNUMBER)" but it's being replaced by empty string.

* I am using TFS 2015 with the legacy version

![image](https://cloud.githubusercontent.com/assets/8670397/26009359/dcb79434-371e-11e7-9d72-0114ebbc9f4b.png)

![image](https://cloud.githubusercontent.com/assets/8670397/26009384/f188a59c-371e-11e7-93f1-c8467ae10f6d.png)

![image](https://cloud.githubusercontent.com/assets/8670397/26009459/486e6892-371f-11e7-9580-f714ce61bd74.png)

**Comment by qetza** [comment]
Hi,
You're not using the correct format for the variables values, you're using a mixed of parameter format and powershell script format.

- the build number predefined variable is `$(Build.BuildNumber)`
- there is no predefined for the current date(`$(Date)` is only available in the build number format) but you can use a PowerShell script task to dynamically create a variable before executing the replace token task: 

`Write-Host "##vso[task.setvariable variable=VersionDate]$([DateTime]::Now.ToString('dd/MM/yyyy'))"`

Here is the list of predefined variables and the syntax to use when using in parameters:
https://www.visualstudio.com/en-us/docs/build/define/variables#predefined-variables

**Comment by lcmassena** [comment]
Thanks for your quickly response!
This was a perfect solution.
