### ISSUE TITLE
Root Directory NAS location seems to fail - 

### ISSUE THREAD

**Issue by plraustin** [qetza/vsts-replacetokens-task#40]
Root Directory:  \ \MyServer\TFSBuildDrop\DS\Dev\POAAdmin-Dev\20170602.6\drop\_PublishedWebsites\POAAdmin\_configs\Dev\

Target Files:  *.config

returns error no file found for pattern

**Comment by qetza** [comment]
Hi @plraustin,
I've never tested with files on network shares. I'll do some testing and see if there's something to fix.

In the meantime, could you activate debug logs (setting variable system.debug to true) and share the output for the replace token tasks?

Thanks,

**Comment by qetza** [comment]
Hi @plraustin,
Version 2.2.0 which was published should fix the network share issue.
