### ISSUE TITLE
UNC Path with glob pattern replacement

### ISSUE THREAD

**Issue by enterprisebug** [qetza/vsts-replacetokens-task#41]
given is a UNC path like **\\\\servername\\ApplicationX**

When trying to replace a file with glob pattern like  _**\\*.config_ it says that it doesn't find the file.

When we map the UNC to a network drive it works. May you fix that?

**Comment by qetza** [comment]
Hi @enterprisebug,
Version 2.2.0 which was published should fix the network share issue.

**Comment by enterprisebug** [comment]
Hi @qetza ,
thanks for the quick fix!
We have tested it successfully!
We really appreciate it!
