### ISSUE TITLE
Release Fails with Empty Variable

### ISSUE THREAD

**Issue by AndrewJWaite** [qetza/vsts-replacetokens-task#45]
Specifying an empty Release variable causes the release to fail with the error:

##[error]variable not found:

This is with the following task settings:

Missing variables > Action = fail
Advanced > Empty value = *nothing/I removed the present value of (empty)*

**Comment by qetza** [comment]
Hi Andrew,
Do you mean that if you have an empty variable name as a token (ie `#{}#`) then you get the error?

This would be consistent with your settings as the task cannot find a release variable with an empty name so it executes the missing variable action which is fail. (not finding a release variable or having the release variable value empty is the same).

The empty value parameter is to support the scenario where you declare a release variable but you explicitly want to replace with an empty value (to avoid confusion with the variable not being declared). 

So if you have a token `#{myvar}#` and want to replace it with nothing then you:
- declare a release variable `myvar` with a value `(empty)` (or whatever placeholder value you want)
- define `(empty)` (or whatever placeholder value you want) as the empty value 

Hope this helps.

**Comment by AndrewJWaite** [comment]
Thanks for the reply @qetza.

The behaviour I'm seeing is with declaring a release variable **without** a value. The build will fail with the above error.

We are using the naming format: **#{myvar}**

I have tried changing the settings from **(empty)** to just being blank but the build still fails.

**Comment by qetza** [comment]
So this is expected as the SDK don't allows me to distinguish between a undeclared variable and a declared variable with an empty value. Both scenarios will trigger the `Missing variables > Action` which you configured to `fail` to fail the build :smile: 

If what you want is replace your token `#{myvar}` with an empty value defined in variable `myvar` then you should set your variable to `(empty)`. This will not trigger the missing variable action as the variable has a value and as you have set the value to the `Empty value` placeholder the task will replace your token with an empty value.

**Comment by motob** [comment]
@qetza 
I was having the same issue and adding (empty) in the release variable did cause the token replace to ignore it! Thanks!

**Comment by qetza** [comment]
Hi @motob, glad it's working for you now :)
