### ISSUE TITLE
backslash on mac build host failing

### ISSUE THREAD

**Issue by morten-nielsen** [qetza/vsts-replacetokens-task#50]
Using backslash in _Target files_ seems not supported when running this task on a Mac build host.
The task will not error, in ln 140 the targetFiles array seems to be empty, so nothing is printed to the log.
![pasted image at 2017_11_01 02_48 pm](https://user-images.githubusercontent.com/28894879/32277959-6bd32d4a-bf14-11e7-94f0-cc7d9ae471db.png)

**Comment by qetza** [comment]
Hi,

Is it working if you put a forward slash `/`? If yes i'll update the tooltip and default value to use a forward slash.

Thanks for reporting the issue.

**Comment by morten-nielsen** [comment]
Yes, it works with forward slash.
