### ISSUE TITLE
Suggestion: escape file path JSON file

### ISSUE THREAD

**Issue by jeanfrancoislarente** [qetza/vsts-replacetokens-task#52]
Hello,

I'm trying to use Replace Tokens to set a file path in a .json file.
My token is @@assets.root@@ and my variable has a normal file path. If this wasn't a .json file everything behaves as it should. However as you know in json the paths need to be escaped.

C:\my-path needs to be `c:\\my-path.`

Just hoping that this would make it in future versions (logic to escape paths when target is .json extension).

**Comment by qetza** [comment]
Hi Jean-Francois,
The task doesn't do any analysis on the file type or the values but only plain text parsing and replace so i don't see how to add this request.

Could you escape the value in the variable directly?

**Comment by jeanfrancoislarente** [comment]
Problem is I use built-in VSTS variables (such as $(System.ArtifactsDirectory) ) as part of my variable value which itself isn't escaped.

My workaround was to create a PowerShell task to set those variables in my .json file - but that defeats the purpose of (trying) to use tokens and a nice extension like this one.

**Comment by samuelhl** [comment]
Hi @jeanfrancoislarente

I'm curious as to how exactly you used a PowerShell task for this as I've run into the exact same issue using JSONs on TFS2017. If you could go into a bit more detail on your workaround that would be great.

Thanks.

**Comment by jeanfrancoislarente** [comment]
I brute forced it - I just used powershell to explicitly take the parameters and replace them where they need to be set - there is no magical token replacement.

**Comment by samuelhl** [comment]
OK, thanks for the reply.

**Comment by qetza** [comment]
Hi,
Sorry i didn't replied earlier, one solution if you want to use tokens and do escaping would be to:
- use a powershell task to get your variables values, escape them and create new variables with the escaped values
- use the replace token task with token names based on the new variable names

This can be done using vsts agent commands (https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md)

**Comment by jeanfrancoislarente** [comment]
I imagine that would work?
No matter what the scenario is, "\" should become "\\" in a .json target file

**Comment by qetza** [comment]
I just released v2.3.0 of the task which includes the 2 parameters to allow escaping characters.
