### ISSUE TITLE
Nested variable replacement?

### ISSUE THREAD

**Issue by robertmirro** [qetza/vsts-replacetokens-task#55]
Are there any plans to support nested variable replacement so that `__URL_TOKEN__` is replaced as `http://dev/` when released to the `Dev` environment?

For example:
```
URL_TOKEN = $(URL_TOKEN_$(Release.EnvironmentName))
URL_TOKEN_Dev = http://dev/
```

The only way I imagine doing this currently is to simulate a dual-pass scenario by configuring two Replace Token tasks and changing the above to:

```
URL_TOKEN = __URL_TOKEN_$(Release.EnvironmentName)__
URL_TOKEN_Dev = http://dev/
```

**Comment by qetza** [comment]
Hi Robert,

You can achieve this with configuring your variable at the environment level:

- define a token `__URL_TOKEN__` and use it in your file
- in your release
  - at the Dev environment scope, configure the variable `URL_TOKEN` with the value `http://dev/`
  - at the Prod environment scope, configure the variable `URL_TOKEN` with the value `http://prod/`

If you prefer, you can use nested variables in VSTS variables:
- in your release, at the release scope, configure the variable `URL_TOKEN` with the value `http://$(Release.EnvironmentName)/`

This will have the value `http://Dev` for the `Dev` environment and `http://Prod/` for the Prod environment

**Comment by robertmirro** [comment]
Thanks for the super fast reply Guillaume!

We currently have our definitions configured like your first option above but it's leading to lots of duplication of process variables across definitions.

I don't think we can use your second option because my initial example was misleading and we're not actually using `$(Release.EnvironmentName)` as part of the url.

This is a more realistic example of the types of process variables that are currently duplicated across many definitions:
```
name - value - scope

URL_SERVICE_ONE - https://001-1.one.host.com/ -Dev
URL_SERVICE_ONE - https://001-2.one.host.com/ - QA
URL_SERVICE_ONE - https://002.one.host.com:8100/ - UAT
URL_SERVICE_ONE - https://003.one.host.com/ - Staging
URL_SERVICE_ONE - https://003.one.host.com:8100/ - Training
URL_SERVICE_ONE - https://003.one.host.com:8200/ - Demo
URL_SERVICE_ONE - https://one.host.com/ - Prod
URL_SERVICE_TWO - https://001-1.two.host.com/ -Dev
URL_SERVICE_TWO - https://001-2.two.host.com/ - QA
URL_SERVICE_TWO - https://002.two.host.com:8100/ - UAT
URL_SERVICE_TWO - https://003.two.host.com/ - Staging
URL_SERVICE_TWO - https://003.two.host.com:8100/ - Training
URL_SERVICE_TWO - https://003.two.host.com:8200/ - Demo
URL_SERVICE_TWO - https://two.host.com/ - Prod
```

I was hoping to remove common variables across definition (such as the above) to variable groups so they can simply be linked to each definition.

**Comment by robertmirro** [comment]
Yikes.  I just realized that the nesting I'm asking for deals with `$()` substitution and is most likely relevant to `vsts-task-lib/task`. :flushed:

**Comment by qetza** [comment]
I understand the burden of managing lots of variables at the environment level. The new UI helps a little bit by displaying everthing in a single screen.

Usually when i can i try to name my resources (dns, folders...) with a common name and using the environment as a prefix or suffix to be able to use the second option i explained. But you don't always have this ability and i then resort to create lots of environment scope variable :(
