### ISSUE TITLE
How to replace version?

### ISSUE THREAD

**Issue by ankitdholakiya** [qetza/vsts-replacetokens-task#56]
Suppose I want to replace the version 5.2.0 to 5.2.1 without any variables declaration, replacing with just find and replace. How can I achieve this using this extension? I can not find useful information to do that. Please suggest.

**Comment by qetza** [comment]
Hi,

The replace token task is getting values from variables only. But if you don’t know the value before execution you can always use a powershell task to run a script that will compute your value and then create a variable a runtime with the value. Here is the doc on how to set a variable at runtime: 
https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/_shared/set-variables-in-scripts?tabs=batch

**Comment by ankitdholakiya** [comment]
Yes, I resolved this by powershell. thank you for your response.
