### ISSUE TITLE
How it is kept secure?

### ISSUE THREAD

**Issue by Glenn-Gidlof** [qetza/vsts-replacetokens-task#57]
When the Token Replacement is sent from the build task to the target file how is the data kept secure?

For example in a .config file I'm replacing a token for $(UserID) and $(Password).  When these are passed to target how are they passed and how are these kept secure.  Or is this data being passed as clear text?

**Comment by qetza** [comment]
Hi,
This is internal work of VSTS/TFS and the build agent but here is what i have understand of the process:
- secret variables are kept encrypted on the server
- they are send encrypted to the build agent when a build is started 
- when a task asks for the value of a secret variable, the value is decrypted and returned to the task

Si that data is decrypted at the last moment. Also communication between the server and the agent is using https.

**Comment by Glenn-Gidlof** [comment]
Thank you.  That is the information I was looking for.  That helps a lot.

Cheers,

-Glenn
