### ISSUE TITLE
Changes in Azure Cloud Services web.config

### ISSUE THREAD

**Issue by henriquepris** [qetza/vsts-replacetokens-task#58]
Hi,

I'm trying to apply Replace Tokens to changes in web.config in Azure Cloud Services. It isn't working because the web.config file is inside the compressed .cspkg file created in the Cloud Services build.

Is there any way to work around this issue?

Regards,
Henrique

**Comment by qetza** [comment]
Hi Henrique,

You can replace tokens in the .cscfg file if you have define your settings there or if you can unzip the cspkg file, replace tokens in your web.config and zip the file again.
