### ISSUE TITLE
Replacing connection string in web.config not working

### ISSUE THREAD

**Issue by Ruud-cb** [qetza/vsts-replacetokens-task#59]
I am encountering a bug I cannot fix.

I have this in web.release.config
![image](https://user-images.githubusercontent.com/10037514/35041818-68d737e0-fb86-11e7-8fed-ebea7be6ee52.png)

It successfully transforms locally:
![image](https://user-images.githubusercontent.com/10037514/35041878-a280f062-fb86-11e7-9f30-7f8f3fb4a8de.png)

Have the task in place: 

![image](https://user-images.githubusercontent.com/10037514/35041940-dedc2540-fb86-11e7-9f67-e1d19190fee4.png)

Also have the variable in place

Logs indicate that the file has been reached and successfully transformed.

After uploading, I see that all other transforms went successfully but only this one is not working.
All others are inside appSettings, that is the only difference I can spot.

![image](https://user-images.githubusercontent.com/10037514/35042105-7dfeeae0-fb87-11e7-83f4-204fc98e6878.png)

Any idea how to fix this?

**Comment by qetza** [comment]
Hi @Ruud-cb,

Sorry for the late reply.

Are all your tokens in the same `web.release.config` file? Because from the configuration that you show the replacement will happen in the `web.config` file only (but maybe you are first applying transformation to the web.config then doing the replace).

Could you share your logs? You can also activate debug logs by setting the `system.debug` variable to `true`.

**Comment by davidsekar** [comment]
> I am encountering a bug I cannot fix.
> 
> I have this in web.release.config
> ![image](https://user-images.githubusercontent.com/10037514/35041818-68d737e0-fb86-11e7-8fed-ebea7be6ee52.png)
> 
> It successfully transforms locally:
> ![image](https://user-images.githubusercontent.com/10037514/35041878-a280f062-fb86-11e7-9f30-7f8f3fb4a8de.png)
> 
> Have the task in place:
> 
> ![image](https://user-images.githubusercontent.com/10037514/35041940-dedc2540-fb86-11e7-9f67-e1d19190fee4.png)
> 
> Also have the variable in place
> 
> Logs indicate that the file has been reached and successfully transformed.
> 
> After uploading, I see that all other transforms went successfully but only this one is not working.
> All others are inside appSettings, that is the only difference I can spot.
> 
> ![image](https://user-images.githubusercontent.com/10037514/35042105-7dfeeae0-fb87-11e7-83f4-204fc98e6878.png)
> 
> Any idea how to fix this?

Hi @Ruud-cb  - I had similar issue and landed over here, but I was disappointed to see this thread is closed without a solution. So I though its best to update this closed issue, to help others who stumble over here latter.

I realized that msbuild was the problem creator. The autoparameterization feature should be disabled in the project for the Replace Token to work as expected.
You can check the instruction in following article, on How to disable the Autoparameterization 
https://davidsekar.com/asp-net/vsts-replace-tokens-task-is-not-replacing-connectionstring

**Comment by jongear** [comment]
Can confirm. Disabling `AutoParameterizationWebConfigConnectionStrings` allows `connectionstring` transforms to work. Thank you @davidsekar 👏 

```
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
...
<AutoParameterizationWebConfigConnectionStrings>False</AutoParameterizationWebConfigConnectionStrings>
  ...
</PropertyGroup>
```
