### ISSUE TITLE
Request: Option to use parameters file instead of variables

### ISSUE THREAD

**Issue by ray13eezy** [qetza/vsts-replacetokens-task#62]
It would be nice to have the option to use a an XML file or something similar so that the values can be source controlled instead of living in TFS variables.

**Comment by qetza** [comment]
Hi,
It could be done but then you would have your secrets in source control available to everyone which is not a good idea.
If you wanted to do this i would propose a 2 steps process:
- in a shell task (cmd, shell, powershell...) read your file and dynamically create TFS variables (see [https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md))
- use the replace token task to replace your tokens with values that you read in the previous task
