### ISSUE TITLE
Replace WebSettings

### ISSUE THREAD

**Issue by ronneylira** [qetza/vsts-replacetokens-task#66]
Hi!

I'm trying to replace in my WebSettings file the following line:

`<add key="VersaoSite" value="#{Build.BuildId}#" />`

I've tried the 

`<add key="VersaoSite" value="#{BUILD_BUILDNUMBER}#" />`

as well

do i need to declare this variable as well ?

Thanks for the help

**Comment by Itfly** [comment]
@ronneylira  Did you solve the problem?
I also got this issue, seems there's no matches found:
```
2018-05-11T09:32:15.7000178Z ##[debug]  /kube-deployment.yml (file)
2018-05-11T09:32:15.7023136Z ##[debug]1 results
2018-05-11T09:32:15.7045381Z ##[debug]found 1 paths
2018-05-11T09:32:15.7067648Z ##[debug]applying include pattern
2018-05-11T09:32:15.7090393Z ##[debug]adjustedPattern: '/wordsmith-demo/kube-deployment.yml/**/*.yml'
2018-05-11T09:32:15.7114313Z ##[debug]0 matches
```

**Comment by Itfly** [comment]
Seems it does not support to specify the file name directly in path.

**Comment by qetza** [comment]
Hi Itfly,
As the parameter name imply it's a directory you must pass. If you do not specify any value it will take the root of the repo.

So get a specific file in a sub folder of your repo use the following settings:
```
Root Directory: {leave empty}
Target files: wordsmith-demo/kube-deployment.yml
```

**Comment by Itfly** [comment]
@qetza I set the root directory to the config file `kube-deployment.yml` parent directory and it works.

**Comment by ronneylira** [comment]
@Itfly I solved on the build, root directory being $(Build.ArtifactStagingDirectory) and target files **\WebSettings.config

the variable defined on the websettings file was set as #{BUILD_BUILDNUMBER}#
