### ISSUE TITLE
ANSI File encoding

### ISSUE THREAD

**Issue by nrubino** [qetza/vsts-replacetokens-task#67]
We have files that are losing characters.  It seems to be because we have ANSI encoding (8bits) which this "Replace Tokens" does not support.  ASCII is only 7bits. 

See example jpg of the characters that are being replaced.
![compare](https://user-images.githubusercontent.com/6493428/39380766-b5c48a3a-4a2d-11e8-9c70-0d87bf2fe651.jpg)

May you also support ANSI?

**Comment by qetza** [comment]
Hi,
Did you try to use utf8 to see if it could work as a workaround?

On the ANSI encoding, this is not an official encoding and can represents different encoding. Which one would you like to have:
- ISO 8859-1
- Windows 1252
- US-ASCII

Here is the full list of encoding i could support based on the library i'm using:
https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings

**Comment by rollercoasterdigital** [comment]
I may have come across another instance of this. I'm replacing tokens in a file and the process corrupts the character "ɵ" which is used in another part of the file. I'm struglling to determine the encoding on the file, could you recommend a way to identify the encoding type?

**Comment by qetza** [comment]
Hi @rollercoasterdigital,
If you use the `auto` value the script will try to determine the encoding used by looking for a BOM at the start of the file. If there is no BOM then ANSI is used.
You can try opening your file with an editor like vs code or notepad++ which will also try to find the encoding for you.
Also try to force utf-8 in the task and see if it works for you.

**Comment by rollercoasterdigital** [comment]
Thanks for that. Both VS Code and Notepad++ are identifying this file as UTF-8. Setting the encoding to UTF-8 appears to have resolved the issue.
