### ISSUE TITLE
Remote token replacement

### ISSUE THREAD

**Issue by FokkoVeegens** [qetza/vsts-replacetokens-task#68]
Hi,

Could you implement remoting for this task? That would make it easier when you're using 1 agent to deploy to multiple remote machines.

Keep up the good work!

**Comment by qetza** [comment]
Hi,

Thanks for the feedback but i'm not sure how i could run a node script remotly.

If you can have a share folder accessible from your agent you could try to use this as the root directory (i haven't tested this).

**Comment by FokkoVeegens** [comment]
Hi,

I'm not a node expert either, so I can't help you there. Using an (administrative) share is an option I have tried which works fine, but is not the most elegant option in my opinion.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to repoen if needed.
