### ISSUE TITLE
Selectable output file.

### ISSUE THREAD

**Issue by andreacassioli** [qetza/vsts-replacetokens-task#71]
It would be nice to replace tokens to obtain an output file instead of replacing in-place.

**Comment by andreacassioli** [comment]
Hi,
what I am thinking about is to replace tokens producing a new file not changing the source:

(input file) - >(outputfile)

**Comment by andreacassioli** [comment]
any further thoughts?

**Comment by qetza** [comment]
Hi,
Just going through opened issues and saw i didn't respond to your last comment. Managing an output file can be tricky especially when using wildcards.

My solution would be that you use another task before to copy your files and then apply the transformation to the copy.

**Comment by andreacassioli** [comment]
Hi, I see the point. I ended up in a similar setting as you describe.
