### ISSUE TITLE
allow using custom regex pattern with named groups 

### ISSUE THREAD

**Issue by johnib** [qetza/vsts-replacetokens-task#72]
Hi,

I'm using the Azure KeyVault task - which defines an env variable per secret name in my vault.
However, the tokens I have in my config contain more than just the secret name, but the vault identifier as well etc.

If I could provide your task a regex pattern of my own, with named groups like you expect in your code (I've read it) - then that would make the whole thing more flexible.

Thanks,
Jonathan

**Comment by qetza** [comment]
Hi @johnib,
If i understand correctly when using the key vault task the variables created are not simply the name of your secret `<secret name>` but the vault identifier and your secret name `<vault id><secret name>` and your tokens are named only after the secret name.
Could you try to just set the token prefix parameter to `#{<vault id>`? If you have other variables without the vault id prefix you could run the task twice, one with the vault id prefix and one without.

Guillaume
