### ISSUE TITLE
Task fails about 50% of the time

### ISSUE THREAD

**Issue by joeyrizza** [qetza/vsts-replacetokens-task#73]
Deployment fails with this error about 50% of the time:
 Could not find file 'C:\agent\_work\_tasks\replacetokens_a8515ec8-7254-4ffd-912c-86772e2b5962\2.3.0\task.json'.

A redeploy with no change in settings will usually work just fine.

> 
> 2018-06-22T14:00:34.6993160Z ##[section]Starting: Release
> 2018-06-22T14:00:34.6993160Z Current agent version: '2.122.2'
> 2018-06-22T14:00:35.0430691Z ##[section]Starting: Initialize Job
> 2018-06-22T14:00:35.0430691Z Prepare release directory.
> 2018-06-22T14:00:35.0430691Z ReleaseId=188, TeamProjectId=70b6aa4a-7969-4cef-846c-c03d8de11bcf, ReleaseDefinitionName=HSDashboard DEV
> 2018-06-22T14:00:35.0586950Z Release folder: C:\agent\_work\r1\a
> 2018-06-22T14:00:35.0743204Z Environment variables available are below.  Note that these environment variables can be referred to in the task (in the ReleaseDefinition) by replacing "_" with "." e.g. AGENT_NAME environment variable can be referenced using Agent.Name in the ReleaseDefinition: 
> 				[AGENT_DEPLOYMENTGROUPID] --> [2]
> 				[AGENT_HOMEDIRECTORY] --> [C:\agent]
> 				[AGENT_ID] --> [8]
> 				[AGENT_JOBNAME] --> [Release]
> 				[AGENT_MACHINENAME] --> [ ... ]
> 				[AGENT_NAME] --> [ ... ]
> 				[AGENT_OS] --> [Windows_NT]
> 				[AGENT_RELEASEDIRECTORY] --> [C:\agent\_work\r1\a]
> 				[AGENT_ROOTDIRECTORY] --> [C:\agent\_work]
> 				[AGENT_SERVEROMDIRECTORY] --> [C:\agent\externals\vstsom]
> 				[AGENT_TEMPDIRECTORY] --> [C:\agent\_work\_temp]
> 				[AGENT_TOOLSDIRECTORY] --> [C:\agent\_work\_tool]
> 				[AGENT_VERSION] --> [2.122.2]
> 				[AGENT_WORKFOLDER] --> [C:\agent\_work]
> 				[AZURE_HTTP_USER_AGENT] --> [TFS_37eaeed6-d714-4af3-b126-df768239f638_release_2_188_533_1]
> 				[BUILD_BUILDID] --> [232]
> 				[BUILD_BUILDNUMBER] --> [20180622.1]
> 				[BUILD_BUILDURI] --> [vstfs:///Build/Build/232]
> 				[BUILD_DEFINITIONID] --> [2]
> 				[BUILD_DEFINITIONNAME] --> [HSDashboard Build Definition]
> 				[BUILD_PROJECTID] --> [70b6aa4a-7969-4cef-846c-c03d8de11bcf]
> 				[BUILD_PROJECTNAME] --> [HSDashboard]
> 				[BUILD_REPOSITORY_ID] --> [70b6aa4a-7969-4cef-846c-c03d8de11bcf]
> 				[BUILD_REPOSITORY_NAME] --> [HSDashboard]
> 				[BUILD_REPOSITORY_PROVIDER] --> [TfsVersionControl]
> 				[BUILD_REQUESTEDFOR] --> [Joe Rizza SU]
> 				[BUILD_REQUESTEDFORID] --> [de237c61-8c6b-45dd-b595-50ca6e82a2a0]
> 				[BUILD_SOURCEBRANCH] --> [$/HSDashboard]
> 				[BUILD_SOURCEBRANCHNAME] --> [HSDashboard]
> 				[BUILD_SOURCEVERSION] --> [1840]
> 				[BUILD_TYPE] --> [Build]
> 				[DWAPITASKFOLDER] --> [C:\scripts]
> 				[DWAPITASKRELEASEFOLDER] --> [C:\scripts\release]
> 				[GACONFIG] --> [UA-110904333-2]
> 				[IDA:ADFSMETADATA] --> [ ... ]
> 				[ISADFS] --> [True]
> 				[ISDEVELOPMENT] --> [True]
> 				[ISOPENID] --> [False]
> 				[ISPRODUCTION] --> [False]
> 				[MSDEPLOY_HTTP_USER_AGENT] --> [TFS_37eaeed6-d714-4af3-b126-df768239f638_release_2_188_533_1]
> 				[RELEASE_ARTIFACTS_HSDASHBOARD_BUILD_DEFINITION_BUILDID] --> [232]
> 				[RELEASE_ARTIFACTS_HSDASHBOARD_BUILD_DEFINITION_BUILDNUMBER] --> [20180622.1]
> 				[RELEASE_ARTIFACTS_HSDASHBOARD_BUILD_DEFINITION_BUILDURI] --> [vstfs:///Build/Build/232]
> 				[RELEASE_ARTIFACTS_HSDASHBOARD_BUILD_DEFINITION_DEFINITIONID] --> [2]
> 				[RELEASE_ARTIFACTS_HSDASHBOARD_BUILD_DEFINITION_DEFINITIONNAME] --> [HSDashboard Build Definition]
> 				[RELEASE_ARTIFACTS_HSDASHBOARD_BUILD_DEFINITION_PROJECTID] --> [70b6aa4a-7969-4cef-846c-c03d8de11bcf]
> 				[RELEASE_ARTIFACTS_HSDASHBOARD_BUILD_DEFINITION_PROJECTNAME] --> [HSDashboard]
> 				[RELEASE_ARTIFACTS_HSDASHBOARD_BUILD_DEFINITION_REPOSITORY_ID] --> [70b6aa4a-7969-4cef-846c-c03d8de11bcf]
> 				[RELEASE_ARTIFACTS_HSDASHBOARD_BUILD_DEFINITION_REPOSITORY_NAME] --> [HSDashboard]
> 				[RELEASE_ARTIFACTS_HSDASHBOARD_BUILD_DEFINITION_REPOSITORY_PROVIDER] --> [TfsVersionControl]
> 				[RELEASE_ARTIFACTS_HSDASHBOARD_BUILD_DEFINITION_REQUESTEDFOR] --> [Joe Rizza SU]
> 				[RELEASE_ARTIFACTS_HSDASHBOARD_BUILD_DEFINITION_REQUESTEDFORID] --> [de237c61-8c6b-45dd-b595-50ca6e82a2a0]
> 				[RELEASE_ARTIFACTS_HSDASHBOARD_BUILD_DEFINITION_SOURCEBRANCH] --> [$/HSDashboard]
> 				[RELEASE_ARTIFACTS_HSDASHBOARD_BUILD_DEFINITION_SOURCEBRANCHNAME] --> [HSDashboard]
> 				[RELEASE_ARTIFACTS_HSDASHBOARD_BUILD_DEFINITION_SOURCEVERSION] --> [1840]
> 				[RELEASE_ARTIFACTS_HSDASHBOARD_BUILD_DEFINITION_TYPE] --> [Build]
> 				[RELEASE_ATTEMPTNUMBER] --> [1]
> 				[RELEASE_DEFINITIONENVIRONMENTID] --> [4]
> 				[RELEASE_DEFINITIONID] --> [2]
> 				[RELEASE_DEFINITIONNAME] --> [HSDashboard DEV]
> 				[RELEASE_DEPLOYMENT_REQUESTEDFOR] --> [Joe Rizza SU]
> 				[RELEASE_DEPLOYMENT_REQUESTEDFOREMAIL] --> [ ... ]
> 				[RELEASE_DEPLOYMENT_REQUESTEDFORID] --> [de237c61-8c6b-45dd-b595-50ca6e82a2a0]
> 				[RELEASE_DEPLOYMENT_STARTTIME] --> [2018-06-22 13:59:57Z]
> 				[RELEASE_DEPLOYMENTID] --> [503]
> 				[RELEASE_DEPLOYPHASEID] --> [700]
> 				[RELEASE_ENVIRONMENTID] --> [533]
> 				[RELEASE_ENVIRONMENTNAME] --> [Development Environment]
> 				[RELEASE_ENVIRONMENTS_DATACENTERWORKERTEST_STATUS] --> [InProgress]
> 				[RELEASE_ENVIRONMENTS_DEVELOPMENT_ENVIRONMENT_STATUS] --> [InProgress]
> 				[RELEASE_ENVIRONMENTS_DWAPITASK_TEST_STATUS] --> [InProgress]
> 				[RELEASE_ENVIRONMENTURI] --> [vstfs:///ReleaseManagement/Environment/533]
> 				[RELEASE_REASON] --> [ContinuousIntegration]
> 				[RELEASE_RELEASEDESCRIPTION] --> [Triggered by HSDashboard Build Definition 20180622.1.]
> 				[RELEASE_RELEASEID] --> [188]
> 				[RELEASE_RELEASENAME] --> [Release-157]
> 				[RELEASE_RELEASEURI] --> [vstfs:///ReleaseManagement/Release/188]
> 				[RELEASE_RELEASEWEBURL] --> [ ... ]
> 				[RELEASE_REQUESTEDFOR] --> [Joe Rizza SU]
> 				[RELEASE_REQUESTEDFOREMAIL] --> [ ... ]
> 				[RELEASE_REQUESTEDFORID] --> [de237c61-8c6b-45dd-b595-50ca6e82a2a0]
> 				[RELEASE_SKIPARTIFACTSDOWNLOAD] --> [False]
> 				[RELEASE_TRIGGERINGARTIFACT_ALIAS] --> [HSDashboard Build Definition]
> 				[REQUESTEDFORID] --> [de237c61-8c6b-45dd-b595-50ca6e82a2a0]
> 				[SEV_ROLESDB] --> [Sev1Test]
> 				[STAGEDIR] --> [C:\agent\stage]
> 				[SYSTEM] --> [deployment]
> 				[SYSTEM_ARTIFACTSDIRECTORY] --> [C:\agent\_work\r1\a]
> 				[SYSTEM_COLLECTIONID] --> [37eaeed6-d714-4af3-b126-df768239f638]
> 				[SYSTEM_CULTURE] --> [en-US]
> 				[SYSTEM_DEFAULTWORKINGDIRECTORY] --> [C:\agent\_work\r1\a]
> 				[SYSTEM_ENABLEACCESSTOKEN] --> [False]
> 				[SYSTEM_HOSTTYPE] --> [deployment]
> 				[SYSTEM_JOBID] --> [fb550db4-ce1b-4c2e-b459-dfe6799afccf]
> 				[SYSTEM_PLANID] --> [ffe82485-3e4e-4837-8779-ede4b2887527]
> 				[SYSTEM_TASKDEFINITIONSURI] --> [ ... ]
> 				[SYSTEM_TEAMFOUNDATIONCOLLECTIONURI] --> [ ... ]
> 				[SYSTEM_TEAMFOUNDATIONSERVERURI] --> [ ... ]
> 				[SYSTEM_TEAMPROJECT] --> [HSDashboard]
> 				[SYSTEM_TEAMPROJECTID] --> [70b6aa4a-7969-4cef-846c-c03d8de11bcf]
> 				[SYSTEM_TIMELINEID] --> [ffe82485-3e4e-4837-8779-ede4b2887527]
> 				[SYSTEM_WORKFOLDER] --> [C:\agent\_work]
> 				[USERNAME] --> [ ... ]
> 				[UTILS03] --> [ ... ]
> 				[UTILS05] --> [ ... ]
> 				[WORKDIR] --> [C:\agent\_work]
> 				[WTREALM] --> [ ... ]
> 2018-06-22T14:00:35.0743204Z Download all required tasks.
> 2018-06-22T14:00:35.0899449Z Downloading task: replacetokens
> 2018-06-22T14:00:35.9493278Z ##[section]Finishing: Initialize Job
> 2018-06-22T14:00:35.9805782Z ##[section]Starting: Download Artifacts
> 2018-06-22T14:00:36.0587034Z Downloading artifact
> 2018-06-22T14:00:36.0587034Z Creating artifacts directory: C:\agent\_work\r1\a
> 2018-06-22T14:00:36.0587034Z Created artifacts directory: C:\agent\_work\r1\a
> 2018-06-22T14:00:36.0743292Z Starting artifacts download...
> 2018-06-22T14:00:36.0743292Z Downloading linked artifact HSDashboard Build Definition of type Build...
> 2018-06-22T14:00:36.0743292Z Ensuring artifact folder C:\agent\_work\r1\a\HSDashboard Build Definition exists and is clean.
> 2018-06-22T14:00:36.0743292Z Preparing to get the list of available artifacts from build
> 2018-06-22T14:00:36.2462107Z Preparing to download artifact: drop
> 2018-06-22T14:00:36.2618668Z Artifact Type: ServerDrop
> 2018-06-22T14:00:36.2618668Z Downloading artifact from file container: #/977/drop to target: C:\agent\_work\r1\a\HSDashboard Build Definition\drop
> 2018-06-22T14:00:36.2618668Z Parallel download limit: 4
> 2018-06-22T14:00:36.2618668Z Download buffer size: 8192
> 2018-06-22T14:00:36.3868328Z Caching items under 'drop' in the file container...
> 2018-06-22T14:00:36.4337084Z Caching complete. (49 ms)
> 2018-06-22T14:00:36.4493330Z Downloading file C:\agent\_work\r1\a\HSDashboard Build Definition\drop\ ... 
> 2018-06-22T14:00:36.4649576Z Downloading file C:\agent\_work\r1\a\HSDashboard Build Definition\drop\ ... 
> 2018-06-22T14:00:36.4649576Z Downloading file C:\agent\_work\r1\a\HSDashboard Build Definition\drop\ ... 
> 2018-06-22T14:00:36.4649576Z Downloading file C:\agent\_work\r1\a\HSDashboard Build Definition\drop\ ... 
> 2018-06-22T14:00:36.4805835Z Downloading file C:\agent\_work\r1\a\HSDashboard Build Definition\drop\ ... 
> 2018-06-22T14:00:36.4805835Z Downloading file C:\agent\_work\r1\a\HSDashboard Build Definition\drop\ ... 
> 2018-06-22T14:00:36.4805835Z Downloading file C:\agent\_work\r1\a\HSDashboard Build Definition\drop\ ... 
> 2018-06-22T14:00:36.4805835Z Downloading file C:\agent\_work\r1\a\HSDashboard Build Definition\drop\ ... 
> 2018-06-22T14:00:36.4962086Z Downloading file C:\agent\_work\r1\a\HSDashboard Build Definition\drop\ ... 
> 2018-06-22T14:00:36.4962086Z Downloading file C:\agent\_work\r1\a\HSDashboard Build Definition\drop\ ... 
> 2018-06-22T14:00:36.4962086Z Downloading file C:\agent\_work\r1\a\HSDashboard Build Definition\drop\ ... 
> 2018-06-22T14:00:36.4962086Z Downloading file C:\agent\_work\r1\a\HSDashboard Build Definition\drop\ ... 
> 2018-06-22T14:00:36.4962086Z Downloading file C:\agent\_work\r1\a\HSDashboard Build Definition\drop\ ... 
> 2018-06-22T14:00:36.5118383Z Downloading file C:\agent\_work\r1\a\HSDashboard Build Definition\drop\ ... 
> 2018-06-22T14:00:36.5118383Z Downloading file C:\agent\_work\r1\a\HSDashboard Build Definition\drop\ ... 
> 2018-06-22T14:00:39.9181272Z Download complete.
> 2018-06-22T14:00:39.9181272Z 15 placed file(s): 15 downloaded, 0 empty
> 2018-06-22T14:00:39.9181272Z 69 MB downloaded at 20243 KB/sec. Download time: 00:00:03.4816557.
> 2018-06-22T14:00:39.9181272Z Downloaded linked artifact HSDashboard Build Definition
> 2018-06-22T14:00:39.9181272Z Finished artifacts download
> 2018-06-22T14:00:39.9181272Z Downloading commits
> 2018-06-22T14:00:39.9337522Z ##[section]Finishing: Download Artifacts
> 2018-06-22T14:00:39.9337522Z ##[section]Starting: Replace tokens in Web.config
> 2018-06-22T14:00:40.1525029Z ##[error]Could not find file 'C:\agent\_work\_tasks\replacetokens_a8515ec8-7254-4ffd-912c-86772e2b5962\2.3.0\task.json'.
> 2018-06-22T14:00:40.1525029Z ##[section]Finishing: Replace tokens in Web.config
> 2018-06-22T14:00:40.1525029Z ##[section]Finishing: Release

**Comment by qetza** [comment]
Hi @joeyrizza,
Sorry for the late reply. The issue seems to come from the agent and not as the task script is not even ran. Looking at the logs this path seems strange `C:\agent_work_tasks\replacetokens_a8515ec8-7254-4ffd-912c-86772e2b5962\2.3.0\task.json`, i think it should be `C:\agent\_work\_tasks\replacetokens_a8515ec8-7254-4ffd-912c-86772e2b5962\2.3.0\task.json`.
Do you have access to the deployment agent machine and look at the files physically?

**Comment by joeyrizza** [comment]
Thank you for your response. I have not been able to replicate this issue since initially posting this. I don’t ha e any idea what happened!

Thanks again!

**Comment by qetza** [comment]
Closing for long inactivity, feel free to repoen if needed.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to repoen if needed.
