### ISSUE TITLE
Token replacement fails 'variable not found' for known-good variable

### ISSUE THREAD

**Issue by CharlesFichter** [qetza/vsts-replacetokens-task#76]
We have a task group variable declared $(AppServiceName) that we use across many tasks (and these work fine, tested and have done many deployments using the variable):
https://gyazo.com/f9ee09b897ca10b5f3580ddbe780bf55

However, when we place a token in a config file as #{AppServiceName}#  we get an error that variable is not found and value is set to empty value=""

The prefix and suffix assignments are correct:
https://gyazo.com/786e0eae9338264b56b8f544cf31e3c7

And in the config file correct:
https://gyazo.com/c5ec044204a9f312484c0f38fde4cf01

Is there something missing in our configuration? Do we need to somehow initialize the variable? It definitely has a value getting populated correctly during deployment as there are many other tasks in the log that successfully use the variable, here is error from log file:

2018-06-29T19:56:46.3219258Z replacing tokens in: G:\a\ppe1a1\w\r73\a\SitecorePlatformArtifact\develop-sitecore-platform-1.0.100\Build\App_Config\Environment\DignityHealth.Foundation.Logging.config
2018-06-29T19:56:46.3222058Z ##[debug]encoding: utf-8
2018-06-29T19:56:46.3383873Z ##[debug]AppServiceName=undefined
2018-06-29T19:56:46.3434835Z ##[warning]variable not found: AppServiceName
2018-06-29T19:56:46.3444436Z ##[debug]Processed: ##vso[task.issue type=warning;]variable not found: AppServiceName

**Comment by qetza** [comment]
Hi @CharlesFichter,
Even though task group parameters are using the same syntax as variables those are only parameters and the replacement is done only in task parameters values before execution, they are not added to the variable lists.
The workaround is to declare your variable with the expected name `AppServiceName` at the build definition level.

**Comment by CharlesFichter** [comment]
Thanks Guillame –
What do we insert for the value though?  AppServiceName will be a generic variable used across the task group, can’t have a static statement assigning a value – and we can’t have a circular reference pointing back to the variable name …?

**Comment by qetza** [comment]
From my tests there are no collision between task group parameter names and variable names. So you can have a task group parameter named `AppServiceName` and a variable named `AppServiceName` with different values.

Another options would be to add a powershell task in your task group which will create/set a variable with the parameter value using the syntax `Write-Host "##vso[task.setvariable variable=AppServiceName;]$(AppServiceName)"`

**Comment by qetza** [comment]
Closing for long inactivity, feel free to repoen if needed.
