### ISSUE TITLE
Can I use this in a .ZIP file?

### ISSUE THREAD

**Issue by sander1095** [qetza/vsts-replacetokens-task#77]
Hello.

The artifact that I want to release is an ASP.NET application, the structure is like this: https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/web-deployment-in-the-enterprise/configuring-parameters-for-web-package-deployment

I believe the config files are in the .ZIP file. I could use multiple build definitions and change values of the web.config at buildtime, but it would be amazing if I could use this plug-in to change the values in the zipfile so I can just use it at release-time. 

Do you know if this is possible?

**Comment by qetza** [comment]
Hi @sander1095,

The task only deals with files and it would be too complicated to support archive files (multiple format, compression type...).

The best solution is to first unzip your package using a dedicated task (you have one for zip files), do the replacement then zip the files back.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to repoen if needed.
