### ISSUE TITLE
Lack of Documentation

### ISSUE THREAD

**Issue by sturk** [qetza/vsts-replacetokens-task#8]
Hi Getza,
thank you writing such a useful extension but since I am not expert in PowerShell is there any example regarding replace value in web.config?

**Comment by qetza** [comment]
Hi sturk,
You can find attached an example of web.config file using token with the default configuration of the task.

Usually I don't tokenize the web.config as I want to be able to run the website in debug mode so the file must be correct; so I create a web.release.config to apply transformation and put token inside this file. The attached zip also contains an example.

[config.zip](https://github.com/qetza/vsts-replacetokens-task/files/254051/config.zip)

**Comment by sturk** [comment]
hi Guillaume,
thank you. it saved me from doing tons of work.

On Sun, May 8, 2016 at 11:54 AM, Guillaume Rouchon <notifications@github.com
