### ISSUE TITLE
Tokenized files

### ISSUE THREAD

**Issue by rontxi** [qetza/vsts-replacetokens-task#80]
It's a problem for me to run projects with tokenized configuration files locally, and It would be nice to be able to use untokenized files. My proposal is to allow tokenized and untokenized to co-exist.  

As an example we can have settings.dev.json and setting.dev.tokenized.json, and in the loop, select the tokenized version and overwrite the untokenized version.

**Comment by qetza** [comment]
Hi @rontxi,

You can also use the `File Patch Build and Release Tasks` (https://marketplace.visualstudio.com/items?itemName=geeklearningio.gl-vsts-tasks-file-patch) to inject tokens in your JSON files before doing the token replacement in your release pipeline.

**Comment by rontxi** [comment]
Hi @qetza , thanks for your response, 
Our json files are complex, with arrays and different variables on each node. It's not an option to use that handy task.

**Comment by qetza** [comment]
Hi @rontxi,

Then your solution to have 2 files is I think the best but you will have to make sure they stay synchronized when you update one.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to repoen if needed.
