### ISSUE TITLE
How to replace a token with different values for different machines?

### ISSUE THREAD

**Issue by lzd6696** [qetza/vsts-replacetokens-task#81]
Hi:

I use TFS 2018 Update 2 as CI/CD server. 
And I use latest Replace Token task as my token replacement solutions.

When I have a token A in my web.config file, and it will be deployed to 2 VMs, VM B and VM C, 
by my tfs release definition.

If I need token A on VM B as Value V1 and token A on VM C as Value V2.

How to do this via Replace Tokens task? 
My idea is using a powershell task to update variable A just prior to Replace Token task. Is this possible?

Please kindly provide or share your idea , it will helps me a lot.

thanks.

**Comment by qetza** [comment]
Hi @lzd6696,

How do you do your deployment on the different VMs, do you have one step for each or do you use deployment groups?

**Comment by lzd6696** [comment]
Hi @qetza 
I Use Deployment Group.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
