### ISSUE TITLE
Replaced tokens should / could be written to log, not replaceable as well (+fail)

### ISSUE THREAD

**Issue by VladdyH** [qetza/vsts-replacetokens-task#82]
I would like to see replaced tokens names in output AND a cross-check (replacement variables against *.config file).

Before switching to this extension I used my own "replaceTokens.ps1 -tokensVariablesFile myReplacements.ps1" script that did some more checks (explanation follows).

What my script did and can be useful for this extension:
1. **enlisted the successfuly replaced tokens to output**
2. did check on *.config after replacing if there are any not replaced tokens left _(this is ensured in the extension by Action-fail already)_
3. **did a cross-check from the other side (tokens-valuesFile if there are any NOT applied tokens left)**

Ad 1 - this feature would make easier revealing eventual errors
Ad 3 - could be realized by defining a common variable prefix among other release variables ( = are there any unused prefixed variables left?)

So in case that point 2 or 3 finds NOT APPLIED tokens/variables the task would FAIL.

**Comment by cmeyertons** [comment]
Second this -- the logging currently is a bit lacking.  It only shows the files it iterated over, not where transformations actually took place.

Would be nice if there was control over verbosity as well:
INFO: what actual replacements took place
VERBOSE: what files were iterated over

this would help provide some clarity and greater confidence that the tool is doing what it is supposed to do.

**Comment by qetza** [comment]
Hi,
You can turn debug logs by setting the variable `system.debug` to `true`. This will display all the file search and all the token replaced with their name and replaced values.

**Comment by VladdyH** [comment]
Hi, I already know about the `system.debug` thing. Nevertheles **that setting affects behavior of other tasks** as well.
Please, check suggestion in attached file.
![replacetokens](https://user-images.githubusercontent.com/26786031/45342808-5416ad80-b59f-11e8-9829-c3d18c8f48bf.PNG)

**Comment by VladdyH** [comment]
Hi @qetza ,

### To your suggestion:
It would be a good beginning - **definitely a move in the right directoin** :+1:

**Elaborating on a test example with 2 replacements in 1 web.config - current version:**
- `system.debug=false` - 10 lines of log (in that: 1=starting, 7="about", **1=web.config path**,1=finishing)
- `system.debug=true` - 92 lines (in that: 1=starting, 7="about", MANY=internal msgs,**1=web.config path, 2=replacements**,1=finishing)
Among all the information the **requested are bolded**.

**Conclusion:**
- if it were just a local variable that would do the same like current `system.debug` does, then better don't do it - it would be simply too much information that are not needed on a daily basis
- like @cmeyertons mentiones - INFO would deliver better experience - clear information about what was done without "internal messages"
- so a parameter with following options would be great: 1) SILENT (tell me nothing), 2) INFO (paths,replacements), 3) DEBUG (everything)


### To point 3 of the OP - "cross-check" for not applied tokens x variables:
**Let me explain the reason I am requesting the cross-check:**
- it is a matter of maintainability
- there wouldn't be any unused replacement variables left in TFS after *.config eventually gets rid of it
- in combination with point 2 (OP) - ensures that every single replacement variable matches a *.config token and vice versa

_(and I am sorry for my english - not my native language)_

**Comment by qetza** [comment]
Hi @VladdyH 

No worry for your english it's not my native language either 😃 

I'll review your feedback and see what i can do to have a better log.

For point 3 i don't see the logic. If you have any token in your file which doesn't have a matching variable then a there's already the missing variables action parameter for this. And going the other way around, display all variables which doesn't match a token would be of no use because you can have a lot of variables which are not linked to a token but used for configuring your deployment or build tasks.

**Comment by VladdyH** [comment]
Hi @qetza 
thank you for not kicking me off yet :)
To point 3:
as there can be plenty of variables for replacement purposes in TFS, I originally suggested to prefix them, thus bringing all together in the variables list (e.g. "**subst**XXXXXX").
The prefix could be used afterwards to check, if all "subst..." variables were applied.

The "missing variables" is checking it from the *.config point of view, whereas my suggestion would check it from the TFS variables for substitution angle.

**Comment by VladdyH** [comment]
Addendum:
Since I realized that TS is not my cup of coffe code, I at least try to suggest 
tl.getVariables()
search for those containing a substitution variables characteristic word ("subst")
check, if all those were used while replacing :)

**Comment by qetza** [comment]
Hi @VladdyH,

I understand your use case but it seems a really special scenario and in all my usage of the task and discussion i had with other users you are the only one asking for this.
Maybe you could use a script before the transformation to do this check?

**Comment by VladdyH** [comment]
Hi @qetza ,
I will elaborate following your suggestion eventually posting a solution :) 

Thank you for your time!

**Comment by VladdyH** [comment]
So, scripting finished. Since TFS does not pass secured variables to Env so that it could be used flawlesly, there is a drawback - visual (manual) check is inevitable in that case.
The script is in attachment.
