### ISSUE TITLE
Token Replacement on Deployment

### ISSUE THREAD

**Issue by rickyzu** [qetza/vsts-replacetokens-task#83]
Hi, 

We're using WebDeploy to deploy a build package to multiple servers. I was wondering if we can set Tokens to be replaced on deployments instead of builds so the same package can be deployed to multiple environments. Standard VSTS doesn't seem to look at log.configs so was hoping to use ReplaceToken instead.

**Comment by p0onage** [comment]
I've just done this and had alittle bit of a nightmare setting it up. To save you time see my release steps 
![image](https://user-images.githubusercontent.com/6472111/49243379-150d3100-f405-11e8-9fdf-0e65664bfe1f.png)

Also don't use ZIP use file archive 👍 issue here : https://stackoverflow.com/a/53542000/3649914
