### ISSUE TITLE
Question: Does this work for environment variables/build variables as well?

### ISSUE THREAD

**Issue by JasonGoemaat** [qetza/vsts-replacetokens-task#84]
I'd like to be able to have it replace a tokens in my index.html with the build number and release name...

**Comment by qetza** [comment]
Hi Jason,
Yes the task works for both build and release pipelines with system and user variables. It does not access environment variables though.

**Comment by ericnewton76** [comment]
Is there any reason for not accessing environment variables?

**Comment by qetza** [comment]
By default the AzDevOps pipeline task SDK is reading variable values from the environment variables so if no variables is defined but an environment variable exists it is used.
