### ISSUE TITLE
How to replace with multiple line?

### ISSUE THREAD

**Issue by Cherishty** [qetza/vsts-replacetokens-task#85]
For one token, it may replace with **multiple** line, or you can see an array,  I know ansible support this feature via __with_item__ , do we support something like this?
I try `\n` but not work

**Comment by qetza** [comment]
Hi David,
Unfortunatly the azure pipelines variables don't support multiline values so currently the task doesn't have any support for multiline values.
What would you expect from this feature? Just replacing the token with a multiline value or something more like iterating through each values?

**Comment by Cherishty** [comment]
Yes, one token to multi-line is exactly what I want.
Any suggestion or workaround?

**Comment by qetza** [comment]
Hi @Cherishty,
To have multiline values i would suggest using a specific token in your value like `\n` then using a powershell task before the replace task to read your variables values and replace the token with an actual new line then update the variable.
You should be able to do this using commands:
https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/commands.md

**Comment by qetza** [comment]
Closing for long inactivity, feel free to repoen if needed.
