### ISSUE TITLE
Saving of the file failing

### ISSUE THREAD

**Issue by xhead** [qetza/vsts-replacetokens-task#86]
At line 189, there is a call fs.writeFileSync that looks to be failing on my release server. The task completes and doesn't report any error, but the actual file hasn't been changed. I even added a second call to a different file name (in the index.js file on the agent) and that file didn't appear either. 

I'm attaching my index.js file with a bunch of debug code in it, and the VSTS log file of the task result. The before and after output of the content variable is correct, and the encoding of the content variable is working. The file doesn't get overwritten (and the .bak file doesn't get created). 

The files are not read-only. 

Do you have any suggestions for debugging this further?

[index.js.txt](https://github.com/qetza/vsts-replacetokens-task/files/2429762/index.js.txt)
[tasklog_4.log](https://github.com/qetza/vsts-replacetokens-task/files/2429769/tasklog_4.log)
![capture](https://user-images.githubusercontent.com/19212199/46233966-5c5e3f00-c33a-11e8-9753-461d86b3e00e.PNG)

**Comment by qetza** [comment]
Hi @xhead,

I never saw this issue, i'll look into the library to see what could explain this. Did you look to make sure that executing user has write permission on the folder?

**Comment by xhead** [comment]
The task is writing the file that was part of the artifact download which happened earlier in the release. That would be using the same identity as this task, the release agent service account, right? That's my assumption.

But no, I didn't check that. I will.

Mike



Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by qetza** [comment]
Closing for long inactivity, feel free to repoen if needed.
