### ISSUE TITLE
Need support for secured variables

### ISSUE THREAD

**Issue by xhead** [qetza/vsts-replacetokens-task#87]
If a variable is protected, the script does not get its value. When you use a protected variable elsewhere, you can use the $(secret.MyPassword) notation.

Perhaps this is by design?

**Comment by qetza** [comment]
Hi @xhead,

Secret variables are supported but i saw in the log of your other issue that you have a typo with password token: `#{PhoebeSqlPassword)#` should be `#{PhoebeSqlPassword}#` (not a closing parenthesis but a closing curly bracket).

I'm going to look at your other issue as i've never ran into this (files not written).

**Comment by qetza** [comment]
Closing for long inactivity, feel free to repoen if needed.
