### ISSUE TITLE
How can update tokens in bulk?

### ISSUE THREAD

**Issue by mohansgithub** [qetza/vsts-replacetokens-task#88]
We have 100+ Token . is there any way to download the token values in some format and update it back again upload it to VSTS ?

**Comment by qetza** [comment]
Hi @mohansgithub,

Do you mean a way to export all your release or build variables to edit them in bulk and send them back?
I think the only way to do this is through the Azure DevOps REST APIs

**Comment by qetza** [comment]
Closing for long inactivity, feel free to repoen if needed.
