### ISSUE TITLE
Leave tokens in if not found

### ISSUE THREAD

**Issue by essenius** [qetza/vsts-replacetokens-task#9]
I'd like to take a 2-phase approach in replacing variables - one during build, and one during deployment. The issue I now run into is that if the variable for a token is not found, it is replaced by an empty string. That means I cannot run the second phase since there are no more tokens to be replaced.

Would it be possible to introduce the possibility to leave tokens as-is if the corresponding variable is not found?

E.g. if I have a line 
``` APP_FOLDER=#{Deploy.AppPath}#\#{AppFolder}# ```

and if ```Deploy.AppPath``` does not exist and ```AppFolder``` equals ```foo```, then this is what I would like to end up with:

``` APP_FOLDER=#{Deploy.AppPath}#\foo ```

That would allow me to use the resulting file as input for the second phase during deployment, which is when ```Deploy.AppPath``` is defined, so that would then take care of the rest.

But at the moment, I get 

``` APP_FOLDER=\foo ```

Also, it would be nice if there is an option to silently ignore unmatched tokens in the log - I expect some of them not to be found, so that doesn't require a warning.

**Comment by qetza** [comment]
@essenius i'll think about adding an option to keep unmatched tokens and change the diagnostics (maybe some selection between None/Warn/Error)
In the meantime what you can do is have 2 sets of tokens:
- #{...}# for token to replace during build
- @{...}@ for token to replace during deploy

Just configure the advanced arguments of task accordingly

**Comment by essenius** [comment]
That's exactly what I did (even using the @ sign :-) ). The downside is that you will need to know in advance whether the variable is substituted during build or during deployment. But as a workaround it does the job.

**Comment by qetza** [comment]
Release 1.3.0 was published on the marketplace and contains the parameters to support your requests:
- you can specify `silently continue` in `Action` to avoid any log (except verbose) on missing variables
- you can check `Keep token` to keep the token on missing variables
