### ISSUE TITLE
token replace xamarin ios build 

### ISSUE THREAD

**Issue by gabsterdev1** [qetza/vsts-replacetokens-task#90]
Hi
Hopefully I am doing something wrong. I have pipeline that I build both android and ios (xamarin)

I have created a variable called build.dev with a value of  "Production" and  I have a class  "BuildEnv.cs" 
 `
    public class BuildEnv
    {
        public const string  CurrentBuildEnvironment="#{build.env}#";
    }`

The replacement works when I  build  the android app but not when I build the ios?
any ideas?
thanks

**Comment by qetza** [comment]
Hi @gabsterdev1,
I'm not sure i understand, your are running 2 builds in the same pipeline with different configuration (one after another) or 1 build twice with different parameters?

**Comment by qetza** [comment]
Closing for long inactivity, feel free to repoen if needed.
