### ISSUE TITLE
Tokens Not Being Replaced

### ISSUE THREAD

**Issue by varonfelder** [qetza/vsts-replacetokens-task#92]
I am experiencing an issue where variables aren't being replaced.  With my current set up it is replacing the variables in the connection string and app settings but not in the endpoint address element.  

This works
```
<connectionStrings>
    <add name="ConnectionString" connectionString="#{ConnectionString}#" providerName="System.Data.SqlClient"/>
  </connectionStrings>
```

This doesn't work 
```
<system.serviceModel>
    <bindings>
      <basicHttpBinding>
        <binding name="Service" />
      </basicHttpBinding>
      <customBinding>
        <binding name="Service1">
          <textMessageEncoding messageVersion="Soap1" />
          <httpTransport />
        </binding>
      </customBinding>
    </bindings>
    <client>
      <endpoint address="#{ServiceSoapEndPoint}#" binding="basicHttpBinding"
        bindingConfigu`enter code here`ration="ServiceSoap" contract="Service.ServiceSoap"
        name="ServiceSoapEndPoint" />
    </client>
```

**Comment by varonfelder** [comment]
To give more context, I'm attempting to use environment variables.  I two environments set up and I have the task added to one of the environments.  I have the variable set up and the scope set as that environment on the release pipeline.  In the log I can see that the task runs but nothing is in the output.

**Comment by qetza** [comment]
Hi @varonfelder,
Would it be possible to run the pipeline with debug activated to see more logs? To activate debug log you need to define the variable `system.debug` and assign it a value of `true`.

**Comment by varonfelder** [comment]
Hey qetza,  I went a different path to get this working and took the task off but if it can work with replacing the variable anywhere in the file this would be great.  I may be doing something wrong and if so please let me know and I can change it to try again.  

This was the set up
I have an environment set up in azure devops under a release deployment process
I added a task to that specific deployment for the replace token
I have a variable set up with the scope of that deployment process
For the root folder I navigated down to the drop folder.
I changed the target files to be **/web.config
In the web.config of my source code I had the variable like #{variablename}#


This is from the logs
2018-11-28T15:52:54.2169733Z ##[section]Starting: Replace tokens in **/web.config
2018-11-28T15:52:54.2174315Z ==============================================================================
2018-11-28T15:52:54.2174402Z Task         : Replace Tokens
2018-11-28T15:52:54.2174451Z Description  : Replace tokens in files
2018-11-28T15:52:54.2174501Z Version      : 3.0.0
2018-11-28T15:52:54.2174640Z Author       : Guillaume Rouchon
2018-11-28T15:52:54.2174689Z Help         : v3.0.0 - [More Information](https://github.com/qetza/vsts-replacetokens-task#readme)
2018-11-28T15:52:54.2174744Z ==============================================================================
2018-11-28T15:52:54.5798296Z ##[section]Finishing: Replace tokens in **/web.config

**Comment by p0onage** [comment]
@varonfelder we can't see much from your output you need to enable debug mode to get pull error logging. Set the System.Debug flag to true 

![image](https://user-images.githubusercontent.com/6472111/49243740-f78c9700-f405-11e8-974e-9e1c80a745b5.png)

**Comment by Abe-Froman** [comment]
I started having the same problem this afternoon even though 3 hours earlier it worked. We're using #| & |# as our token delimiters. The value that we expect to be replaced but isn't is:

  buildId: '#|Build.BuildId|#',

[Debug output attached](https://github.com/qetza/vsts-replacetokens-task/files/2631316/debuglog.txt)

**Comment by Abe-Froman** [comment]
I just posted (and subsequently deleted) a me too post before I double-checked our build definition task. Our dev ops guy changed the tokens on me.

Long story short, maybe just double-check your token prefix/suffix values in your pipeline task to make sure it's set to the tokens you expect.

**Comment by qetza** [comment]
@varonfelder the replace token tasks works on all the content of text files, it doesn't do anything special based on the file type so if at least one variable is replaced it means the task found your file and could read it. You can activate debug logs to have a better view of which tokens where found and if a suitable variable was found to replace, you should also double check your token and variable names.

**Comment by varonfelder** [comment]
I have included screenshots to show the setup I have and attached in a file to this post, let me know if there is an issue viewing.  I still have the same issue, do the variables need to be on the build definition or can it be on the release?

[ReproSteps.docx](https://github.com/qetza/vsts-replacetokens-task/files/2633396/ReproSteps.docx)

**Comment by Abe-Froman** [comment]
Try moving your replace tokens task to the first position. 

It seems like what you’re doing is deploying, and then updating the config. This happens on the build agent so the config is not altered on the server where it’s installed.

**Comment by varonfelder** [comment]
I moved it up and saved ran again and same result. I checked the log and didn't see anything different.  I can repost if that helps.

I just want to clarify can this be ran on the release because maybe that's where the issue is?  I'm trying to set a variable that can be changed per environment and I see that Azure now has this functionality built in but it's limited to a few elements in the web config.

**Comment by pranshaggarwal** [comment]
I was facing the same issue. In my case, I was using the wrong pattern to find the file due to which it is unable to find the file and replacing it with the correct pattern solved my pattern.

But I guess it should fail the task if it does not find any file according to the pattern.

**Comment by varonfelder** [comment]
![image](https://user-images.githubusercontent.com/7442684/49400084-2e69f200-f711-11e8-8bb9-a622705cb60f.png)

I'm not sure where that is coming from buy this is a snippet of the prefix and suffix.  Does the Xml variable substituion on the web app deploy task have any impact?

**Comment by varonfelder** [comment]
Unchecking didn't have any impact.  I'm going to set up another project and add the task on that one and see if produces a different result

**Comment by p0onage** [comment]
Okay in your debug logs it shows a testproject.zip you need to extract the files, then run your token replace step and then rezip them up before deploying

**Comment by varonfelder** [comment]
I'm not sure what you are meaning but it sounds like what you are proposing would complicate things as I'm using Azure Devops to handle the deployment which means I would have to add it some powershell code to accomplish that.  I added the task on the build pipeline and it works as expected, it just doesn't at the release pipeline level which is what I was hoping to use it for.

**Comment by qetza** [comment]
Hi @varonfelder,

As p0onage said a webdeploy file is a zip file containing all your website files so the replace token task cannot access your `web.config` file directly. You have 2 solutions:

The first one, as p0onage said, is to unzip, replace, zip back and deploy. To do this you can use the following tasks:
- Extract Files
- Replace Tokens
- Archive Files
- IIS Web App Manage
- IIS Web App Deploy

The second, if your pipeline agent is install on your IIS server where you deploy, is to replace the tokens in the deployed directory. To do this you need to configure the `Replace Tokens` task to set the `Root directory` with the root folder of your deployed website.

**Comment by qetza** [comment]
@p0onage I know it sounds a good idea to have the Replace Tokens task manage zip files but it will add to much of a layer of complexity: which zip files should the task look in? which files in the zip? ...

A better approach would be a clear documentation on how to handle this and how to create a task group do automatically include the 3 needed tasks.

**Comment by varonfelder** [comment]
Thanks for the update, I guess Azure Devops has the ability to do everything mentioned above by checking the xml variable substitution option on the IIS Web App Deploy task in the release.  Even though it's limited I will keep using that for now.  I'm trying to migrate applications over to Azure Devops in my free time  and I'm trying to keep things as simple as possible which is why I hoped that this one task added to the release pipeline would allow me to have environment variables. Since it looks like it's not built to handle that I'm going to go ahead and mark it as closed and hope that maybe one day will work as an added task or microsoft allows support for more elements.

**Comment by nealsu** [comment]
Did the ability to handle zip files ever get added?

**Comment by qetza** [comment]
Hi @nealsu, 
No the task is not supporting zip files. If you need to replace tokens in zip files first unzip your file, do the replace and rezip.
