### ISSUE TITLE
Build Variables

### ISSUE THREAD

**Issue by VaughanJ** [qetza/vsts-replacetokens-task#94]
I have a variable : 
${Build.BinariesDirectory}\WebServices
Which I thought would get evaluted as the path + \webservices.
But it's being treated as a litteral.

What am I doing wrong ?

Thanks

**Comment by msfe** [comment]
Have you tried using parentheses instead? 

$(Build.BinariesDirectory)\WebServices

**Comment by qetza** [comment]
Closing for long inactivity, feel free to repoen if needed.
