### ISSUE TITLE
Replace by json property name

### ISSUE THREAD

**Issue by fouadroumieh** [qetza/vsts-replacetokens-task#95]
Hi.

Is is possible through this task to replace json property by their name. So if there is variable name that matches the property name in json file, the value get overriden. Same as the file transform task by MS is doing (which is not working for me):

> Provide new line separated list of JSON files to substitute the variable values. Files names are to be provided relative to the root folder. 
> To substitute JSON variables that are nested or hierarchical, specify them using JSONPath expressions. 
> 
> For example, to replace the value of ‘ConnectionString’ in the sample below, you need to define a variable as ‘Data.DefaultConnection.ConnectionString’ in the build or release pipeline (or release pipeline's environment). 
> {
>   "Data": {
>     "DefaultConnection": {
>       "ConnectionString": "Server=(localdb)\SQLEXPRESS;Database=MyDB;Trusted_Connection=True"
>     }
>   }
> }
> Variable Substitution is run after configuration transforms. 
> 
> Note: pipeline variables are excluded in substitution.

**Comment by qetza** [comment]
Hi,

No the task is only doing simple regex on text files to replace defined tokens by variables. If you cannot put tokens in your json file you could have a script which would read your file and replace property values with tokens based on their name and then use the replace token task.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
