### ISSUE TITLE
To lower case during transformation

### ISSUE THREAD

**Issue by conrad-chan** [qetza/vsts-replacetokens-task#96]
Is there a way to turn values to lower case (Or other basic transformation) while substituting?

**Comment by qetza** [comment]
Hi,

Currently they are no transformation applied to values. Could you explain me your use case to see if this could be use more broadly and need to be added as a feature?

**Comment by jjburr** [comment]
+1 
I replace tokens with build vars such as branch name in a yaml file, sometimes a branch name has an uppercase in it which causes the deployment to fail as the yaml as it expects values to be in lowercase.

**Comment by qetza** [comment]
I'll see how i could had simple transformation (tolower, toupper) without breaking changes in a future version.

**Comment by unclev** [comment]
With a variable that may be defined in mixed character case I would like it to be used in lower case for some substitutions.

In YAML pipeline as long as the mentioned variable is defined statically, or with the ##vso setVariable command, there can be _another_ variable defined in lower case (with either AzDO pipeline `lower()` expression or in a PowerShell script).

The use case: defining the first variable in web UI (variable group or pipeline variable), and neither of them in the code, - for better maintainability.

_replasetokens_ with transformations would do the work.

**Comment by stoopered** [comment]
This is not available in the UI step yet. When is that planned on being added?

**Comment by qetza** [comment]
Hi @conrad-chan, @jjburr, @unclev, @stoopered,
Version 3.7.0 of the task is released and now supports the following transformations:
- **lower**: make variable value lower case. Example: `#{lower(MyVar)}#`
- **upper**: make variable value upper case. Example: `#{upper(MyVar)}#`
- **noescape**: disable variable value escaping. (this can be used if you want to inject raw JSON or XML for example). Example: `#{noescape(MyVar)}#`

By default the separator after the transformation name are parenthesis `(`and `)` but if needed those can be changed when the transformation feature is enabled.
